/*
 * code_generator.c — 6502→C emitter
 *
 * Design:
 * - Global g_cpu struct (not passed by pointer — simpler)
 * - FLAG_NZ(v) macro sets N and Z
 * - One C statement per 6502 instruction (sometimes two)
 * - JSR → direct C function call: func_C123()
 * - RTS → return
 * - BNE +n → if (!g_cpu.Z) goto label_XXXX
 * - JMP (ind) → call_by_address(nes_read16(ind)); return
 */
#include "code_generator.h"
#include "annotations.h"
#include "cpu6502_decoder.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ---- Helpers ---- */

static void emit_header(FILE *f) {
    fprintf(f,
        "/* AUTO-GENERATED by NESRecomp. DO NOT EDIT. */\n"
        "#include \"nes_runtime.h\"\n"
        "#include \"coroutine.h\"\n"
        "#ifdef RECOMP_STACK_TRACKING\n"
        "#include \"recomp_stack.h\"\n"
        "#endif\n"
        "#ifdef WATCHDOG_ENABLED\n"
        "#include \"watchdog.h\"\n"
        "#endif\n\n"
        "/* Flag helpers */\n"
        "#define FLAG_NZ(v) do { g_cpu.N=((v)>>7)&1; g_cpu.Z=((v)==0)?1:0; } while(0)\n"
        "#define FLAG_NZC_ADD(r,a,b) do { uint16_t _r=(r); g_cpu.C=(_r>0xFF)?1:0; \\\n"
        "    g_cpu.N=((_r>>7)&1); g_cpu.Z=((_r&0xFF)==0)?1:0; \\\n"
        "    g_cpu.V=(~((a)^(b))&((a)^_r)&0x80)?1:0; } while(0)\n"
        "#define FLAG_NZC_SUB(r,a,b) do { int16_t _r=(r); g_cpu.C=(_r>=0)?1:0; \\\n"
        "    g_cpu.N=((_r>>7)&1); g_cpu.Z=((_r&0xFF)==0)?1:0; \\\n"
        "    g_cpu.V=(((a)^(b))&((a)^_r)&0x80)?1:0; } while(0)\n\n"
    );
}

static void emit_forward_decls(FILE *f, const FunctionList *funcs, const NESRom *rom,
                               const GameConfig *cfg) {
    fprintf(f, "/* Forward declarations */\n");
    for (int i = 0; i < funcs->count; i++) {
        uint16_t addr = funcs->entries[i].addr;
        int bank = funcs->entries[i].bank;
        int fixed = rom->prg_banks - 1;
        if (bank == fixed && addr >= 0xC000) {
            fprintf(f, "void func_%04X(void);\n", addr);
        } else {
            fprintf(f, "void func_%04X_b%d(void);\n", addr, bank);
        }
    }
    /* Forward-declare extra_label secondary entry wrappers */
    if (cfg) {
        int fixed = rom->prg_banks - 1;
        for (int i = 0; i < cfg->extra_label_count; i++) {
            uint16_t addr = cfg->extra_labels[i].addr;
            int bank = cfg->extra_labels[i].bank;
            if (bank == fixed && addr >= 0xC000)
                fprintf(f, "void func_%04X(void);\n", addr);
            else
                fprintf(f, "void func_%04X_b%d(void);\n", addr, bank);
        }
    }
    fprintf(f, "\n");
}

/* Emit the operand address computation for a given addressing mode.
 * Returns a C expression string (static buffer — use immediately). */
static const char *operand_addr_expr(AddrMode am, uint8_t op1, uint8_t op2) {
    static char buf[64];
    uint16_t abs16 = op1 | ((uint16_t)op2 << 8);
    switch (am) {
        case AM_ZP:   snprintf(buf, sizeof(buf), "0x%02X", op1); break;
        case AM_ZPX:  snprintf(buf, sizeof(buf), "(0x%02X + g_cpu.X) & 0xFF", op1); break;
        case AM_ZPY:  snprintf(buf, sizeof(buf), "(0x%02X + g_cpu.Y) & 0xFF", op1); break;
        case AM_ABS:  snprintf(buf, sizeof(buf), "0x%04X", abs16); break;
        case AM_ABSX: snprintf(buf, sizeof(buf), "(0x%04X + g_cpu.X) & 0xFFFF", abs16); break;
        case AM_ABSY: snprintf(buf, sizeof(buf), "(0x%04X + g_cpu.Y) & 0xFFFF", abs16); break;
        case AM_INDX: snprintf(buf, sizeof(buf), "nes_read16zp((0x%02X + g_cpu.X) & 0xFF)", op1); break;
        case AM_INDY: snprintf(buf, sizeof(buf), "(nes_read16zp(0x%02X) + g_cpu.Y) & 0xFFFF", op1); break;
        default:      snprintf(buf, sizeof(buf), "0"); break;
    }
    return buf;
}

/* Check if a branch target is a valid instruction-start address within this function.
 * valid_starts[] is the pre-scan list; also checks if tgt == last_instr + size
 * (valid continuation point right after the last scanned instruction). */
static bool is_valid_label_target(uint16_t tgt, const uint16_t *vs, int vc,
                                   const NESRom *rom, int bank) {
    for (int i = 0; i < vc; i++)
        if (vs[i] == tgt) return true;
    if (vc == 0) return false;
    /* Check if tgt is exactly one instruction past the last scanned instruction */
    uint16_t last = vs[vc - 1];
    uint8_t op = rom_read(rom, bank, last);
    int sz = g_opcode_table[op].size;
    if (sz <= 0) sz = 1;
    return (tgt == (uint16_t)(last + sz));
}

/* Check if a RAM address has a read hook registered in game.cfg */
static bool is_ram_read_hooked(const GameConfig *cfg, uint16_t addr) {
    for (int i = 0; i < cfg->ram_read_hook_count; i++)
        if (cfg->ram_read_hooks[i].addr == addr) return true;
    return false;
}

/* Check if an address is a registered function entry point */
static bool is_func_entry(const FunctionList *funcs, uint16_t addr) {
    for (int i = 0; i < funcs->count; i++) {
        if (funcs->entries[i].addr == addr) return true;
    }
    return false;
}

/* Translate an SRAM address to ROM address via game config sram_map.
 * Returns the ROM address (>= $8000) on success, or 0 if not mapped. */
static uint16_t codegen_sram_translate(const GameConfig *cfg, uint16_t addr, int *out_bank) {
    for (int i = 0; i < cfg->sram_map_count; i++) {
        const SramMap *m = &cfg->sram_maps[i];
        if (addr >= m->sram_start && addr < m->sram_start + m->size) {
            *out_bank = m->bank;
            return m->rom_start + (addr - m->sram_start);
        }
    }
    return 0;
}

/* Check if an address is a valid inline_dispatch table entry:
 * either in ROM range ($8000+) or in a configured SRAM map range
 * whose translated ROM address has a generated function. */
static int is_valid_dispatch_target(const GameConfig *cfg, uint16_t addr,
                                     const FunctionList *funcs) {
    if (addr >= 0x8000) return 1;
    int sram_bank = -1;
    uint16_t rom_addr = codegen_sram_translate(cfg, addr, &sram_bank);
    if (!rom_addr) return 0;
    /* Only accept SRAM targets that have a known function — prevents
     * random ROM data from extending the table past its real end. */
    if (funcs && function_list_contains(funcs, rom_addr, sram_bank)) return 1;
    return 0;
}

/* Emit C for one instruction. Returns bytes consumed.
 * sched_reset_addr: if non-zero, we're inside a coroutine scheduler function.
 * This is the address of the LDX #$FF; TXS stack-reset (scheduler loop entry).
 * JMP(ind) and resume-RTS will goto this label instead of returning. */
static int emit_instruction(FILE *f, const NESRom *rom, int bank,
                            uint16_t pc, uint16_t func_base, int fixed_bank,
                            const FunctionList *funcs,
                            const uint16_t *valid_starts, int valid_count,
                            const GameConfig *cfg, int sram_sourced,
                            int effective_bank,
                            const uint16_t *merge_partners, int merge_partner_count,
                            const uint16_t *emitted_addrs, int emitted_count,
                            uint16_t sched_reset_addr) {
    uint8_t opcode = rom_read(rom, bank, pc);
    const OpcodeEntry *e = &g_opcode_table[opcode];
    uint8_t op1 = (e->size > 1) ? rom_read(rom, bank, pc+1) : 0;
    uint8_t op2 = (e->size > 2) ? rom_read(rom, bank, pc+2) : 0;
    uint16_t abs16 = op1 | ((uint16_t)op2 << 8);

    /* Label for branch targets.
     * Emit maybe_trigger_vblank(2) at every instruction boundary — on real
     * 6502, NMI is only sampled between instructions, never mid-instruction.
     * nes_read/nes_write now only increment the bus-op counter (bus_tick),
     * so VBlank can only fire here at the instruction boundary. */
    fprintf(f, "    /* $%04X: %02X */ maybe_trigger_vblank(%d); ", pc, opcode, e->cycles);

    if (e->mnemonic == MN_ILLEGAL) {
        fprintf(f, "/* ILLEGAL $%02X — skip %d */\n", opcode, e->size);
        return e->size;
    }

    switch (e->mnemonic) {
        /* Load/Store */
        case MN_LDA:
            if (e->addr_mode == AM_IMM)
                fprintf(f, "g_cpu.A = 0x%02X; FLAG_NZ(g_cpu.A);\n", op1);
            else if (e->addr_mode == AM_ABS && is_ram_read_hooked(cfg, abs16))
                fprintf(f, "g_cpu.A = game_ram_read_hook(0x%04X, 0x%04X, nes_read(0x%04X)); FLAG_NZ(g_cpu.A);\n", pc, abs16, abs16);
            else
                fprintf(f, "g_cpu.A = nes_read(%s); FLAG_NZ(g_cpu.A);\n",
                        operand_addr_expr(e->addr_mode, op1, op2));
            break;
        case MN_LDX:
            if (e->addr_mode == AM_IMM)
                fprintf(f, "g_cpu.X = 0x%02X; FLAG_NZ(g_cpu.X);\n", op1);
            else if (e->addr_mode == AM_ABS && is_ram_read_hooked(cfg, abs16))
                fprintf(f, "g_cpu.X = game_ram_read_hook(0x%04X, 0x%04X, nes_read(0x%04X)); FLAG_NZ(g_cpu.X);\n", pc, abs16, abs16);
            else
                fprintf(f, "g_cpu.X = nes_read(%s); FLAG_NZ(g_cpu.X);\n",
                        operand_addr_expr(e->addr_mode, op1, op2));
            break;
        case MN_LDY:
            if (e->addr_mode == AM_IMM)
                fprintf(f, "g_cpu.Y = 0x%02X; FLAG_NZ(g_cpu.Y);\n", op1);
            else if (e->addr_mode == AM_ABS && is_ram_read_hooked(cfg, abs16))
                fprintf(f, "g_cpu.Y = game_ram_read_hook(0x%04X, 0x%04X, nes_read(0x%04X)); FLAG_NZ(g_cpu.Y);\n", pc, abs16, abs16);
            else
                fprintf(f, "g_cpu.Y = nes_read(%s); FLAG_NZ(g_cpu.Y);\n",
                        operand_addr_expr(e->addr_mode, op1, op2));
            break;
        case MN_LAX:
            if (e->addr_mode == AM_IMM)
                fprintf(f, "g_cpu.A = g_cpu.X = 0x%02X; FLAG_NZ(g_cpu.A);\n", op1);
            else
                fprintf(f, "g_cpu.A = g_cpu.X = nes_read(%s); FLAG_NZ(g_cpu.A);\n",
                        operand_addr_expr(e->addr_mode, op1, op2));
            break;
        case MN_STA:
            fprintf(f, "nes_write(%s, g_cpu.A);\n",
                    operand_addr_expr(e->addr_mode, op1, op2));
            break;
        case MN_STX:
            fprintf(f, "nes_write(%s, g_cpu.X);\n",
                    operand_addr_expr(e->addr_mode, op1, op2));
            break;
        case MN_STY:
            fprintf(f, "nes_write(%s, g_cpu.Y);\n",
                    operand_addr_expr(e->addr_mode, op1, op2));
            break;

        /* Transfers */
        case MN_TAX: fprintf(f, "g_cpu.X = g_cpu.A; FLAG_NZ(g_cpu.X);\n"); break;
        case MN_TAY: fprintf(f, "g_cpu.Y = g_cpu.A; FLAG_NZ(g_cpu.Y);\n"); break;
        case MN_TXA: fprintf(f, "g_cpu.A = g_cpu.X; FLAG_NZ(g_cpu.A);\n"); break;
        case MN_TYA: fprintf(f, "g_cpu.A = g_cpu.Y; FLAG_NZ(g_cpu.A);\n"); break;
        case MN_TSX: fprintf(f, "g_cpu.X = g_cpu.S; FLAG_NZ(g_cpu.X);\n"); break;
        case MN_TXS:
            fprintf(f, "g_cpu.S = g_cpu.X;\n");
            /* Coroutine scheduler: LDX #$FF; TXS resets the stack.
             * Emit setjmp so coroutine_yield() can longjmp back here. */
            if (sched_reset_addr && pc == sched_reset_addr + 2) {
                fprintf(f, "    coroutine_scheduler_setjmp(); /* scheduler loop entry */\n");
            }
            break;

        /* Stack — bus_tick for each stack byte access (real 6502 does 1 bus
         * cycle per stack push/pull; JSR/RTS also push/pull via the stack
         * but their ticks are handled in the JSR/RTS emitters below). */
        case MN_PHA:
            fprintf(f, "g_ram[0x100 + g_cpu.S] = g_cpu.A; g_cpu.S--;\n");
            break;
        case MN_PLA:
            fprintf(f, "g_cpu.S++; g_cpu.A = g_ram[0x100 + g_cpu.S]; FLAG_NZ(g_cpu.A);\n");
            break;
        case MN_PHP:
            fprintf(f, "{ uint8_t p = (g_cpu.N<<7)|(g_cpu.V<<6)|0x30|(g_cpu.D<<3)|(g_cpu.I<<2)|(g_cpu.Z<<1)|g_cpu.C;\n"
                       "  g_ram[0x100 + g_cpu.S] = p; g_cpu.S--; }\n");
            break;
        case MN_PLP:
            fprintf(f, "{ g_cpu.S++; uint8_t p = g_ram[0x100 + g_cpu.S];\n"
                       "  g_cpu.N=(p>>7)&1; g_cpu.V=(p>>6)&1; g_cpu.D=(p>>3)&1;\n"
                       "  g_cpu.I=(p>>2)&1; g_cpu.Z=(p>>1)&1; g_cpu.C=p&1; }\n");
            break;

        /* ALU */
        case MN_ADC: {
            const char *src = (e->addr_mode==AM_IMM)
                ? "0x%02X" : "nes_read(%s)";
            if (e->addr_mode == AM_IMM)
                fprintf(f, "{ uint16_t r = g_cpu.A + 0x%02X + g_cpu.C; FLAG_NZC_ADD(r,g_cpu.A,0x%02X); g_cpu.A=r&0xFF; }\n", op1, op1);
            else
                fprintf(f, "{ uint8_t m=nes_read(%s); uint16_t r=g_cpu.A+m+g_cpu.C; FLAG_NZC_ADD(r,g_cpu.A,m); g_cpu.A=r&0xFF; }\n",
                        operand_addr_expr(e->addr_mode, op1, op2));
            (void)src;
            break;
        }
        case MN_SBC:
            if (e->addr_mode == AM_IMM)
                fprintf(f, "{ uint8_t m=0x%02X; int16_t r=g_cpu.A-m-(1-g_cpu.C); FLAG_NZC_SUB(r,g_cpu.A,m); g_cpu.A=r&0xFF; }\n", op1);
            else if (e->addr_mode == AM_ABS && is_ram_read_hooked(cfg, abs16))
                fprintf(f, "{ uint8_t m=game_ram_read_hook(0x%04X, 0x%04X, nes_read(0x%04X)); int16_t r=g_cpu.A-m-(1-g_cpu.C); FLAG_NZC_SUB(r,g_cpu.A,m); g_cpu.A=r&0xFF; }\n", pc, abs16, abs16);
            else
                fprintf(f, "{ uint8_t m=nes_read(%s); int16_t r=g_cpu.A-m-(1-g_cpu.C); FLAG_NZC_SUB(r,g_cpu.A,m); g_cpu.A=r&0xFF; }\n",
                        operand_addr_expr(e->addr_mode, op1, op2));
            break;
        case MN_AND:
            if (e->addr_mode == AM_IMM)
                fprintf(f, "g_cpu.A &= 0x%02X; FLAG_NZ(g_cpu.A);\n", op1);
            else
                fprintf(f, "g_cpu.A &= nes_read(%s); FLAG_NZ(g_cpu.A);\n",
                        operand_addr_expr(e->addr_mode, op1, op2));
            break;
        case MN_ORA:
            if (e->addr_mode == AM_IMM)
                fprintf(f, "g_cpu.A |= 0x%02X; FLAG_NZ(g_cpu.A);\n", op1);
            else
                fprintf(f, "g_cpu.A |= nes_read(%s); FLAG_NZ(g_cpu.A);\n",
                        operand_addr_expr(e->addr_mode, op1, op2));
            break;
        case MN_EOR:
            if (e->addr_mode == AM_IMM)
                fprintf(f, "g_cpu.A ^= 0x%02X; FLAG_NZ(g_cpu.A);\n", op1);
            else
                fprintf(f, "g_cpu.A ^= nes_read(%s); FLAG_NZ(g_cpu.A);\n",
                        operand_addr_expr(e->addr_mode, op1, op2));
            break;

        /* Shifts */
        case MN_ASL:
            if (e->addr_mode == AM_ACC)
                fprintf(f, "g_cpu.C = (g_cpu.A>>7)&1; g_cpu.A = (g_cpu.A<<1)&0xFF; FLAG_NZ(g_cpu.A);\n");
            else
                fprintf(f, "{ uint16_t a=%s; uint8_t v=nes_read(a); g_cpu.C=(v>>7)&1; v=(v<<1)&0xFF; nes_write(a,v); FLAG_NZ(v); }\n",
                        operand_addr_expr(e->addr_mode, op1, op2));
            break;
        case MN_LSR:
            if (e->addr_mode == AM_ACC)
                fprintf(f, "g_cpu.C = g_cpu.A&1; g_cpu.A >>= 1; FLAG_NZ(g_cpu.A);\n");
            else
                fprintf(f, "{ uint16_t a=%s; uint8_t v=nes_read(a); g_cpu.C=v&1; v>>=1; nes_write(a,v); FLAG_NZ(v); }\n",
                        operand_addr_expr(e->addr_mode, op1, op2));
            break;
        case MN_ROL:
            if (e->addr_mode == AM_ACC)
                fprintf(f, "{ uint8_t c=g_cpu.C; g_cpu.C=(g_cpu.A>>7)&1; g_cpu.A=((g_cpu.A<<1)|c)&0xFF; FLAG_NZ(g_cpu.A); }\n");
            else
                fprintf(f, "{ uint16_t a=%s; uint8_t v=nes_read(a); uint8_t c=g_cpu.C; g_cpu.C=(v>>7)&1; v=((v<<1)|c)&0xFF; nes_write(a,v); FLAG_NZ(v); }\n",
                        operand_addr_expr(e->addr_mode, op1, op2));
            break;
        case MN_ROR:
            if (e->addr_mode == AM_ACC)
                fprintf(f, "{ uint8_t c=g_cpu.C; g_cpu.C=g_cpu.A&1; g_cpu.A=((g_cpu.A>>1)|(c<<7))&0xFF; FLAG_NZ(g_cpu.A); }\n");
            else
                fprintf(f, "{ uint16_t a=%s; uint8_t v=nes_read(a); uint8_t c=g_cpu.C; g_cpu.C=v&1; v=((v>>1)|(c<<7))&0xFF; nes_write(a,v); FLAG_NZ(v); }\n",
                        operand_addr_expr(e->addr_mode, op1, op2));
            break;

        /* Inc/Dec */
        case MN_INC:
            fprintf(f, "{ uint16_t a=%s; uint8_t v=(nes_read(a)+1)&0xFF; nes_write(a,v); FLAG_NZ(v); }\n",
                    operand_addr_expr(e->addr_mode, op1, op2));
            break;
        case MN_DEC:
            fprintf(f, "{ uint16_t a=%s; uint8_t v=(nes_read(a)-1)&0xFF; nes_write(a,v); FLAG_NZ(v); }\n",
                    operand_addr_expr(e->addr_mode, op1, op2));
            break;
        case MN_INX: fprintf(f, "g_cpu.X = (g_cpu.X+1)&0xFF; FLAG_NZ(g_cpu.X);\n"); break;
        case MN_DEX: fprintf(f, "g_cpu.X = (g_cpu.X-1)&0xFF; FLAG_NZ(g_cpu.X);\n"); break;
        case MN_INY: fprintf(f, "g_cpu.Y = (g_cpu.Y+1)&0xFF; FLAG_NZ(g_cpu.Y);\n"); break;
        case MN_DEY: fprintf(f, "g_cpu.Y = (g_cpu.Y-1)&0xFF; FLAG_NZ(g_cpu.Y);\n"); break;

        /* Compare */
        case MN_CMP:
            if (e->addr_mode == AM_IMM)
                fprintf(f, "{ int r=g_cpu.A-0x%02X; g_cpu.C=(g_cpu.A>=0x%02X)?1:0; FLAG_NZ(r&0xFF); }\n", op1, op1);
            else if (e->addr_mode == AM_ABS && is_ram_read_hooked(cfg, abs16))
                fprintf(f, "{ uint8_t m=game_ram_read_hook(0x%04X, 0x%04X, nes_read(0x%04X)); int r=g_cpu.A-m; g_cpu.C=(g_cpu.A>=m)?1:0; FLAG_NZ(r&0xFF); }\n", pc, abs16, abs16);
            else
                fprintf(f, "{ uint8_t m=nes_read(%s); int r=g_cpu.A-m; g_cpu.C=(g_cpu.A>=m)?1:0; FLAG_NZ(r&0xFF); }\n",
                        operand_addr_expr(e->addr_mode, op1, op2));
            break;
        case MN_CPX:
            if (e->addr_mode == AM_IMM)
                fprintf(f, "{ int r=g_cpu.X-0x%02X; g_cpu.C=(g_cpu.X>=0x%02X)?1:0; FLAG_NZ(r&0xFF); }\n", op1, op1);
            else if (e->addr_mode == AM_ABS && is_ram_read_hooked(cfg, abs16))
                fprintf(f, "{ uint8_t m=game_ram_read_hook(0x%04X, 0x%04X, nes_read(0x%04X)); int r=g_cpu.X-m; g_cpu.C=(g_cpu.X>=m)?1:0; FLAG_NZ(r&0xFF); }\n", pc, abs16, abs16);
            else
                fprintf(f, "{ uint8_t m=nes_read(%s); int r=g_cpu.X-m; g_cpu.C=(g_cpu.X>=m)?1:0; FLAG_NZ(r&0xFF); }\n",
                        operand_addr_expr(e->addr_mode, op1, op2));
            break;
        case MN_CPY:
            if (e->addr_mode == AM_IMM)
                fprintf(f, "{ int r=g_cpu.Y-0x%02X; g_cpu.C=(g_cpu.Y>=0x%02X)?1:0; FLAG_NZ(r&0xFF); }\n", op1, op1);
            else if (e->addr_mode == AM_ABS && is_ram_read_hooked(cfg, abs16))
                fprintf(f, "{ uint8_t m=game_ram_read_hook(0x%04X, 0x%04X, nes_read(0x%04X)); int r=g_cpu.Y-m; g_cpu.C=(g_cpu.Y>=m)?1:0; FLAG_NZ(r&0xFF); }\n", pc, abs16, abs16);
            else
                fprintf(f, "{ uint8_t m=nes_read(%s); int r=g_cpu.Y-m; g_cpu.C=(g_cpu.Y>=m)?1:0; FLAG_NZ(r&0xFF); }\n",
                        operand_addr_expr(e->addr_mode, op1, op2));
            break;
        case MN_BIT:
            fprintf(f, "{ uint8_t m=nes_read(%s); g_cpu.Z=(g_cpu.A&m)?0:1; g_cpu.N=(m>>7)&1; g_cpu.V=(m>>6)&1; }\n",
                    operand_addr_expr(e->addr_mode, op1, op2));
            break;

        /* Branches — detect cross-function targets:
         *   1. target < func_base: backward into a different function
         *   2. target is a registered function entry: branch into another func
         *   3. target is mid-instruction: not a valid label start in this function
         * In all three cases emit as conditional tail-call, not goto. */
        #define EMIT_BRANCH(cond_str) do { \
            int8_t _off = (int8_t)op1; \
            uint16_t _tgt = (uint16_t)(pc + 2 + _off); \
            bool _valid_local = is_valid_label_target(_tgt, valid_starts, valid_count, rom, bank); \
            /* Cross-function if target is not in this function's valid_starts    \
             * (pre-scan now stops at the function boundary, so valid_starts       \
             * accurately reflects the function's extent). No need to check        \
             * is_func_entry — valid_starts is the ground truth. */                \
            bool _cross = !_valid_local || (_tgt < func_base); \
            if (_cross) { \
                fprintf(f, "if (" cond_str ") { call_by_address(0x%04X); return; }\n", _tgt); \
            } else if (_tgt <= pc) { \
                /* Backward branch (loop) — emit VBlank trigger + watchdog check */ \
                fprintf(f, "if (" cond_str ") {\n    maybe_trigger_vblank(2);\n#ifdef WATCHDOG_ENABLED\n    watchdog_check();\n#endif\n    goto label_%04X;\n    }\n", _tgt); \
            } else { \
                fprintf(f, "if (" cond_str ") goto label_%04X;\n", _tgt); \
            } \
        } while(0)
        case MN_BCC: EMIT_BRANCH("!g_cpu.C"); break;
        case MN_BCS: EMIT_BRANCH("g_cpu.C");  break;
        case MN_BEQ: EMIT_BRANCH("g_cpu.Z");  break;
        case MN_BNE: EMIT_BRANCH("!g_cpu.Z"); break;
        case MN_BMI: EMIT_BRANCH("g_cpu.N");  break;
        case MN_BPL: EMIT_BRANCH("!g_cpu.N"); break;
        case MN_BVC: EMIT_BRANCH("!g_cpu.V"); break;
        case MN_BVS: EMIT_BRANCH("g_cpu.V");  break;
        #undef EMIT_BRANCH

        /* Jumps */
        case MN_JSR: {
            /* Check against game-config trampolines (e.g. JSR $F859 for Faxanadu MMC1).
             * The inline_bytes after the JSR are data [bank, addr_lo, addr_hi], not code.
             * Inline the full dispatch+call+restore sequence and consume 3+inline_bytes. */
            {
                const TrampolineEntry *tramp = NULL;
                for (int ti = 0; ti < cfg->trampoline_count; ti++) {
                    if (abs16 == cfg->trampolines[ti].addr) { tramp = &cfg->trampolines[ti]; break; }
                }
                if (tramp) {
                    uint8_t disp_bank = rom_read(rom, bank, pc + 3);
                    uint8_t disp_lo   = rom_read(rom, bank, pc + 4);
                    uint8_t disp_hi   = rom_read(rom, bank, pc + 5);
                    uint16_t disp_addr = (disp_lo | ((uint16_t)disp_hi << 8)) + tramp->addr_adjust;
                    const char *breg = (tramp->bank_reg == 'A') ? "A" : "X";
                    fprintf(f, "/* trampoline $%04X dispatch: bank=%d addr=$%04X */\n",
                            tramp->addr, disp_bank, disp_addr);
                    fprintf(f, "{ uint8_t _sa=g_cpu.A,_sx=g_cpu.X,_sy=g_cpu.Y;\n");
                    if (tramp->bank_save_addr >= 0x8000)
                        fprintf(f, "  uint8_t _sbank=nes_read(0x%04X);\n", tramp->bank_save_addr);
                    else
                        fprintf(f, "  uint8_t _sbank=g_ram[0x%04X];\n", tramp->bank_save_addr);
                    fprintf(f, "  g_cpu.%s=0x%02X; func_%04X();\n", breg, disp_bank, tramp->bs_fn_addr);
                    fprintf(f, "  g_cpu.A=_sa; g_cpu.X=_sx; g_cpu.Y=_sy;\n");
                    if (cfg->push_all_jsr)
                        fprintf(f, "  if (!call_by_address(0x%04X)) g_cpu.S += 2;\n", disp_addr);
                    else
                        fprintf(f, "  call_by_address(0x%04X);\n", disp_addr);
                    fprintf(f, "  _sa=g_cpu.A;\n");
                    fprintf(f, "  g_cpu.%s=_sbank; func_%04X();\n", breg, tramp->bs_fn_addr);
                    fprintf(f, "  g_cpu.A=_sa; }\n");
                    return 3 + tramp->inline_bytes;
                }
            }
            /* Check against inline_dispatch: JSR to an indexed-dispatch routine.
             * Bytes after the JSR are a 2-byte LE address table indexed by A.
             * Table ends when hi byte < 0x80.  Emit a switch on g_cpu.A. */
            {
                const InlineDispatch *idsp = NULL;
                for (int ti = 0; ti < cfg->inline_dispatch_count; ti++) {
                    if (abs16 == cfg->inline_dispatches[ti].addr) { idsp = &cfg->inline_dispatches[ti]; break; }
                }
                if (idsp) {
                    uint16_t tpc = pc + 3;
                    int entry_count = 0;
                    /* Count entries: valid targets are ROM ($8000+) or SRAM-mapped
                     * with a known function at the translated ROM address. */
                    while (1) {
                        uint8_t lo = rom_read(rom, bank, tpc);
                        uint8_t hi = rom_read(rom, bank, tpc + 1);
                        uint16_t addr = (uint16_t)lo | ((uint16_t)hi << 8);
                        if (!is_valid_dispatch_target(cfg, addr, funcs)) break;
                        tpc += 2;
                        entry_count++;
                    }
                    /* Determine which bank to use for switchable-range targets.
                     * Scan backward from this JSR TableJump for the nearest
                     * LDA #imm; JSR SwitchBank pattern (within ~20 bytes). */
                    int dispatch_bank = -1;
                    if (bank != fixed_bank) {
                        dispatch_bank = bank;
                    } else {
                        /* Fixed bank: check inline_dispatch bank hints in config.
                         * Then fall back to backward scan for LDA #imm; JSR SwitchBank.
                         * Look for the dominating bank switch by scanning backward
                         * up to 64 bytes, skipping conditional branch targets. */
                        for (int bk = 5; bk <= 64; bk++) {
                            if (pc < (uint16_t)(0xC000 + bk)) break;
                            uint16_t probe = (uint16_t)(pc - bk);
                            /* Skip if this location is after a conditional branch
                             * (indicating we're in a branch-taken path, not the
                             * main code flow).  Heuristic: if a JMP (4C) immediately
                             * precedes this JSR SwitchBank, it's a tail-call from a
                             * branch and the bank is not the dominating one. */
                            for (int bi2 = 0; bi2 < cfg->bank_switch_count; bi2++) {
                                uint16_t bs_addr = cfg->bank_switches[bi2].addr;
                                if (rom_read(rom, bank, probe) == 0x20 &&
                                    rom_read(rom, bank, probe + 1) == (bs_addr & 0xFF) &&
                                    rom_read(rom, bank, probe + 2) == ((bs_addr >> 8) & 0xFF) &&
                                    probe >= 2 && rom_read(rom, bank, probe - 2) == 0xA9) {
                                    int bval = rom_read(rom, bank, probe - 1);
                                    if (bval < fixed_bank) {
                                        /* Check if a JMP follows this bank switch within 6 bytes.
                                         * If so, this is a branch-only bank switch (tail call),
                                         * not the dominating one. Skip it. */
                                        int is_tail = 0;
                                        for (int fwd = 3; fwd <= 8; fwd++) {
                                            if (rom_read(rom, bank, probe + fwd) == 0x4C) {
                                                is_tail = 1; break;
                                            }
                                        }
                                        if (!is_tail) {
                                            dispatch_bank = bval;
                                            goto dispatch_bank_found;
                                        }
                                    }
                                }
                            }
                        }
                        dispatch_bank_found:;
                    }
                    fprintf(f, "/* inline_dispatch $%04X: %d entries (bank=%d) */\n",
                            idsp->addr, entry_count, dispatch_bank);
                    /* inline_dispatch is a computed JMP: the dispatch routine does
                     * PLA/PLA then JMP (indirect), bypassing any code after the table.
                     * Emit `return` after each case (not `break`) so the containing
                     * function terminates immediately after the dispatch. */
                    /* Validate dispatch_bank: every switchable-range target
                     * must have a generated function for that bank.  If any
                     * target is missing, fall back to call_by_address(). */
                    if (dispatch_bank >= 0 && funcs) {
                        uint16_t vpc = pc + 3;
                        for (int vi = 0; vi < entry_count; vi++) {
                            uint8_t vlo = rom_read(rom, bank, vpc);
                            uint8_t vhi = rom_read(rom, bank, vpc + 1);
                            uint16_t vdest = (uint16_t)vlo | ((uint16_t)vhi << 8);
                            if (vdest >= 0x8000 && vdest < 0xC000) {
                                if (!function_list_contains(funcs, vdest, dispatch_bank)) {
                                    dispatch_bank = -1; /* fall back */
                                    break;
                                }
                            }
                            vpc += 2;
                        }
                    }
                    fprintf(f, "switch(g_cpu.A) {\n");
                    tpc = pc + 3;
                    for (int ei = 0; ei < entry_count; ei++) {
                        uint8_t lo = rom_read(rom, bank, tpc);
                        uint8_t hi = rom_read(rom, bank, tpc + 1);
                        uint16_t dest = (uint16_t)lo | ((uint16_t)hi << 8);
                        fprintf(f, "  case %d: ", ei);
                        if (dest >= 0xC000) {
                            fprintf(f, "func_%04X(); return;\n", dest);
                        } else if (dest >= 0x8000) {
                            if (dispatch_bank >= 0) {
                                /* Bank known from register propagation, validated */
                                fprintf(f, "func_%04X_b%d(); return;\n", dest, dispatch_bank);
                            } else if (bank != fixed_bank) {
                                fprintf(f, "func_%04X_b%d(); return;\n", dest, bank);
                            } else {
                                /* Fixed bank, no bank-switch or missing targets: runtime */
                                fprintf(f, "call_by_address(0x%04X); return;\n", dest);
                            }
                        } else {
                            /* Check if SRAM-mapped address */
                            int sram_bank = -1;
                            uint16_t rom_addr = codegen_sram_translate(cfg, dest, &sram_bank);
                            if (rom_addr) {
                                if (rom_addr >= 0xC000) {
                                    fprintf(f, "func_%04X(); return;\n", rom_addr);
                                } else {
                                    fprintf(f, "func_%04X_b%d(); return;\n", rom_addr, sram_bank);
                                }
                            } else {
                                fprintf(f, "call_by_address(0x%04X); return;\n", dest);
                            }
                        }
                        tpc += 2;
                    }
                    fprintf(f, "  default: nes_log_inline_miss(0x%04X, g_cpu.A); return;\n", pc);
                    fprintf(f, "}\n");
                    return (int)(tpc - pc);
                }
            }
            /* Check against nop_jsr: JSR to skip entirely (emit nothing) */
            for (int ni = 0; ni < cfg->nop_jsr_count; ni++) {
                if (abs16 == cfg->nop_jsrs[ni]) {
                    fprintf(f, "/* nop_jsr $%04X — skipped */\n", abs16);
                    return 3;
                }
            }
            /* Push 6502 return address before call, matching real JSR behavior.
             * Needed for any code that reads the 6502 stack (e.g., coroutine
             * schedulers using TXS/TSX + PLA/RTS to save/resume contexts).
             * JSR pushes (PC+2) hi then lo; RTS pops and adds 1.
             * push_all_jsr: every JSR pushes.  push_jsr: only listed targets. */
            bool did_push_jsr = cfg->push_all_jsr;
            if (!did_push_jsr) {
                for (int ni = 0; ni < cfg->push_jsr_count; ni++) {
                    if (abs16 == cfg->push_jsrs[ni]) { did_push_jsr = true; break; }
                }
            }
            if (did_push_jsr) {
                /* Universal bail detection: save S before push so we
                 * can detect post-call stack unwind (PLA PLA RTS etc.).
                 * If S changed after the call, the callee unwound one
                 * or more frames — propagate by returning immediately.
                 * Subsumes per-function stack_bail_func / cond_bail_func. */
                fprintf(f, "{ uint8_t _cbs = g_cpu.S; ");
                uint16_t ret_addr = pc + 2; /* 6502 JSR pushes PC+2 (last byte of JSR) */
                fprintf(f, "g_ram[0x100 + g_cpu.S] = 0x%02X; g_cpu.S--; ",
                        (ret_addr >> 8) & 0xFF);
                fprintf(f, "g_ram[0x100 + g_cpu.S] = 0x%02X; g_cpu.S--; ",
                        ret_addr & 0xFF);
            }
            /* Check against inline_pointer: JSR to a routine that reads 2
             * inline bytes as a data pointer into zero page. */
            {
                const InlinePointer *ipp = NULL;
                for (int ti = 0; ti < cfg->inline_pointer_count; ti++) {
                    if (abs16 == cfg->inline_pointers[ti].addr) { ipp = &cfg->inline_pointers[ti]; break; }
                }
                if (ipp) {
                    uint8_t lo = rom_read(rom, bank, pc + 3);
                    uint8_t hi = rom_read(rom, bank, pc + 4);
                    fprintf(f, "/* inline_pointer $%04X: load $%02X%02X into $%02X/$%02X */\n",
                            ipp->addr, hi, lo, ipp->zp_lo, ipp->zp_hi);
                    fprintf(f, "g_ram[0x%02X] = 0x%02X; g_ram[0x%02X] = 0x%02X;\n",
                            ipp->zp_lo, lo, ipp->zp_hi, hi);
                    if (!ipp->call) {
                        /* getPointer_fromStack leaves Y=2 after reading 2 bytes */
                        fprintf(f, "g_cpu.Y = 2; FLAG_NZ(g_cpu.Y);\n");
                    }
                    if (ipp->call) {
                        if (abs16 >= 0xC000)
                            fprintf(f, "func_%04X();\n", abs16);
                        else if (bank == fixed_bank) {
                            if (cfg->push_all_jsr)
                                fprintf(f, "if (!call_by_address(0x%04X)) g_cpu.S += 2;\n", abs16);
                            else
                                fprintf(f, "call_by_address(0x%04X);\n", abs16);
                        } else
                            fprintf(f, "func_%04X_b%d();\n", abs16, bank);
                    }
                    return 5;
                }
            }
            if (abs16 >= 0xC000) {
                fprintf(f, "func_%04X();\n", abs16);
            } else if (abs16 >= 0x8000) {
                if (bank == fixed_bank || sram_sourced) {
                    /* Cross-bank call from fixed bank, OR call from SRAM-sourced
                     * function: bank is determined at runtime by the mapper, so
                     * dispatch via call_by_address.  SRAM functions run from RAM
                     * and bank-switch during execution, so JSR targets in the
                     * switchable bank range must use dynamic dispatch. */
                    if (cfg->push_all_jsr)
                        fprintf(f, "if (!call_by_address(0x%04X)) g_cpu.S += 2;\n", abs16);
                    else
                        fprintf(f, "call_by_address(0x%04X);\n", abs16);
                } else {
                    fprintf(f, "func_%04X_b%d();\n", abs16, bank);
                }
            } else {
                /* JSR to non-ROM address (RAM/PPU): dispatch at runtime */
                if (cfg->push_all_jsr)
                    fprintf(f, "if (!call_by_address(0x%04X)) g_cpu.S += 2;\n", abs16);
                else
                    fprintf(f, "call_by_address(0x%04X);\n", abs16);
            }
            /* Universal bail propagation: if S changed after the call
             * (callee did PLA PLA RTS or similar stack unwind), propagate
             * the unwind by returning immediately.
             *
             * Skip bail for call_by_address() targets: dynamic dispatch may
             * reach coroutine yields or context switches that legitimately
             * change S mid-call.  Bail propagation is only reliable for
             * direct function calls where we know the target's behavior. */
            if (did_push_jsr) {
                if (cfg->push_all_jsr) {
                    /* push_all_jsr mode: skip bail propagation entirely.
                     * Games using push_all_jsr have coroutine schedulers
                     * that legitimately manipulate S (yield/resume), and
                     * maybe_trigger_vblank can fire NMI/IRQ mid-call which
                     * temporarily changes S.  Bail detection is incompatible
                     * with these patterns — false positives cause the entire
                     * call chain to unwind. */
                    fprintf(f, "}\n");
                } else {
                    fprintf(f, "if (g_cpu.S != _cbs) {\n#ifdef RECOMP_STACK_TRACKING\n    recomp_stack_pop();\n#endif\n    return; } }\n");
                }
            }
            break;
        }
        case MN_JMP:
            if (e->addr_mode == AM_ABS) {
                if (abs16 >= 0xC000) {
                    if (abs16 == func_base && pc == func_base) {
                        /* JMP $self at function start: true idle spin (single-instr).
                         * while(1) polls VBlank without recursion. */
                        fprintf(f, "while(1) { maybe_trigger_vblank(2); }\n");
                    } else if (abs16 == func_base) {
                        /* JMP to own entry from within body: loop-back. */
                        fprintf(f, "goto label_%04X;\n", abs16);
                    } else if (abs16 >= func_base && abs16 < pc) {
                        /* JMP to an address already emitted within this function body.
                         * Use goto to avoid mutual tail-call recursion: if $C0BC's body
                         * includes $C0CB as a label, JMP $C0CB must be a goto, not a
                         * call to the separate func_C0CB() — otherwise they recurse
                         * every frame and overflow the C stack.
                         * Verify the label actually exists (function may have gaps). */
                        bool label_exists = false;
                        for (int ei = 0; ei < emitted_count; ei++) {
                            if (emitted_addrs[ei] == abs16) { label_exists = true; break; }
                        }
                        if (label_exists)
                            fprintf(f, "goto label_%04X;\n", abs16);
                        else
                            fprintf(f, "maybe_trigger_vblank(2); func_%04X(); return;\n", abs16);
                    } else if (pc >= 0xC003 &&
                               rom_read(rom, bank, pc - 3) == 0xBA /* TSX */ &&
                               rom_read(rom, bank, pc - 2) == 0x96 /* STX zp,Y */) {
                        /* Coroutine yield pattern: TSX; STX $NN,Y; JMP $scheduler.
                         * The function saved the stack pointer to a channel table and
                         * is jumping to the scheduler loop (which never returns to the
                         * caller). Emit coroutine_yield() which longjmps back to the
                         * scheduler's setjmp point. */
                        fprintf(f, "coroutine_yield(); return;\n");
                    } else {
                        /* Check push_jmp: bail-containing targets need a dummy
                         * push so the bail's RTS has something safe to pop.
                         * source=0 matches any JMP site; nonzero matches only that PC. */
                        int need_jmp_push = 0;
                        for (int ji = 0; ji < cfg->push_jmp_count; ji++) {
                            if (abs16 == cfg->push_jmps[ji].target &&
                                (cfg->push_jmps[ji].source == 0 || cfg->push_jmps[ji].source == pc))
                            { need_jmp_push = 1; break; }
                        }
                        if (need_jmp_push) {
                            fprintf(f, "maybe_trigger_vblank(2); g_ram[0x100+g_cpu.S]=0; g_cpu.S--; g_ram[0x100+g_cpu.S]=0; g_cpu.S--; func_%04X(); return;\n", abs16);
                        } else {
                            fprintf(f, "maybe_trigger_vblank(2); func_%04X(); return;\n", abs16);
                        }
                    }
                } else if (abs16 >= 0x8000) {
                    /* Check if target is a merge partner (use goto, not function call) */
                    bool is_merge = false;
                    for (int mi = 0; mi < merge_partner_count; mi++) {
                        if (abs16 == merge_partners[mi]) { is_merge = true; break; }
                    }
                    /* For overlapping entries within a merge_range that can't be
                     * fully merged: their JMP to a target within the range becomes
                     * a call to the canonical merged function. This is safe because
                     * the merged function's internal loop-back is a goto, and its
                     * final RTS properly pops the caller's return address. */
                    if (bank == fixed_bank || sram_sourced) {
                        /* push_jmp check for cross-bank JMP via dispatch */
                        int need_jmp_push = 0;
                        for (int ji = 0; ji < cfg->push_jmp_count; ji++) {
                            if (abs16 == cfg->push_jmps[ji].target &&
                                (cfg->push_jmps[ji].source == 0 || cfg->push_jmps[ji].source == pc))
                            { need_jmp_push = 1; break; }
                        }
                        if (need_jmp_push) {
                            fprintf(f, "maybe_trigger_vblank(2); g_ram[0x100+g_cpu.S]=0; g_cpu.S--; g_ram[0x100+g_cpu.S]=0; g_cpu.S--; call_by_address(0x%04X); return;\n", abs16);
                        } else {
                            fprintf(f, "maybe_trigger_vblank(2); call_by_address(0x%04X); return;\n", abs16);
                        }
                    } else if (abs16 == func_base && pc == func_base) {
                        /* JMP $self at function start: true idle spin. */
                        fprintf(f, "while(1) { maybe_trigger_vblank(2); }\n");
                    } else if (abs16 == func_base || is_merge) {
                        /* JMP to own entry or merge partner: loop-back via goto. */
                        fprintf(f, "maybe_trigger_vblank(2);\n    goto label_%04X;\n", abs16);
                    } else {
                        /* push_jmp check for same-bank JMP */
                        int need_jmp_push = 0;
                        for (int ji = 0; ji < cfg->push_jmp_count; ji++) {
                            if (abs16 == cfg->push_jmps[ji].target &&
                                (cfg->push_jmps[ji].source == 0 || cfg->push_jmps[ji].source == pc))
                            { need_jmp_push = 1; break; }
                        }
                        if (need_jmp_push) {
                            fprintf(f, "maybe_trigger_vblank(2); g_ram[0x100+g_cpu.S]=0; g_cpu.S--; g_ram[0x100+g_cpu.S]=0; g_cpu.S--; func_%04X_b%d(); return;\n", abs16, bank);
                        } else {
                            fprintf(f, "maybe_trigger_vblank(2); func_%04X_b%d(); return;\n", abs16, bank);
                        }
                    }
                } else {
                    /* JMP to non-ROM address: dispatch at runtime */
                    fprintf(f, "maybe_trigger_vblank(2); call_by_address(0x%04X); return;\n", abs16);
                }
            } else {
                /* JMP (ind) — dispatch */
                if (abs16 < 0x100) {
                    /* Zero-page indirect: read the pointer BEFORE triggering VBlank. */
                    if (sched_reset_addr) {
                        /* Coroutine scheduler START: create fiber, dispatch to
                         * coroutine entry, loop back when it yields. */
                        fprintf(f, "{ uint16_t _jt = nes_read16zp(0x%02X); maybe_trigger_vblank(2); coroutine_start(g_ram[0x91], _jt); goto label_%04X; }\n",
                                (uint8_t)abs16, sched_reset_addr);
                    } else {
                        fprintf(f, "{ uint16_t _jt = nes_read16zp(0x%02X); maybe_trigger_vblank(2); call_by_address(_jt); return; }\n", (uint8_t)abs16);
                    }
                } else {
                    fprintf(f, "{ uint16_t _jt = nes_read16(0x%04X); maybe_trigger_vblank(2); call_by_address(_jt); return; }\n", abs16);
                }
            }
            break;
        case MN_RTS:
            /* Coroutine scheduler RESUME: after TXS restored the coroutine's
             * stack pointer, PLA/TAY/PLA/TAX/RTS resumes the coroutine.
             * The RTS should dispatch to the saved PC on the 6502 stack,
             * then loop back to the scheduler when the coroutine yields.
             * Pattern: 68 A8 68 AA 60 (PLA TAY PLA TAX RTS) with sched active. */
            if (sched_reset_addr && pc >= 4 &&
                rom_read(rom, bank, pc - 4) == 0x68 /* PLA */ &&
                rom_read(rom, bank, pc - 3) == 0xA8 /* TAY */ &&
                rom_read(rom, bank, pc - 2) == 0x68 /* PLA */ &&
                rom_read(rom, bank, pc - 1) == 0xAA /* TAX */) {
                /* Coroutine resume: longjmp to the saved coroutine context.
                 * The 6502 stack pop (PLA/PLA/RTS) is conceptual — the real
                 * resume is via longjmp to where the coroutine last yielded.
                 * Pop the 6502 return address to keep the simulated stack correct,
                 * but dispatch via coroutine_resume, not call_by_address.
                 * Channel index comes from $91 (set by scheduler at $FECB). */
                fprintf(f, "{ g_cpu.S += 2; /* skip RTS addr */ coroutine_resume(g_ram[0x91]); goto label_%04X; }\n", sched_reset_addr);
                break;
            }
            /* Detect 4-PHA dispatch: LDA #cont_hi/PHA / LDA #cont_lo/PHA /
             * LDA tbl_hi,Y/PHA / LDA tbl_lo,Y/PHA / RTS.
             * PHAs at pc-12, pc-9, pc-5, pc-1.  Continuation = pc+1.
             * The 2 cont bytes must be cleaned off the stack unconditionally
             * (target may have internal PHA/PLA imbalance — can't be conditional). */
            if (pc >= 0x800D &&
                rom_read(rom, bank, pc-1)  == 0x48 &&
                rom_read(rom, bank, pc-5)  == 0x48 &&
                rom_read(rom, bank, pc-9)  == 0x48 &&
                rom_read(rom, bank, pc-12) == 0x48) {
                fprintf(f, "{ uint8_t _s4=g_cpu.S; g_cpu.S++; uint8_t _lo=g_ram[0x100+g_cpu.S]; g_cpu.S++; uint8_t _hi=g_ram[0x100+g_cpu.S]; call_by_address(((uint16_t)_hi<<8|_lo)+1); g_cpu.S=(uint8_t)(_s4+4); } goto label_%04X;\n    ", (uint16_t)(pc+1));
            /* Detect 2-PHA RTS-as-JMP: LDA hi/PHA / LDA lo/PHA / RTS.
             * Also detect "outer continuation" pattern: function starts with
             * LDA #cont_hi/PHA / LDA #cont_lo/PHA, then does computation, then
             * LDA tbl_hi/PHA / LDA tbl_lo/PHA / RTS.  The 4-PHA detector above
             * misses this because the PHAs are not at fixed offsets (computation
             * breaks the pc-9/pc-12 spacing).  After calling the inner handler,
             * we must also call the static outer continuation. */
            } else if (pc >= 0x8001 && rom_read(rom, bank, pc - 1) == 0x48 /* PHA */) {
                /* Check for outer continuation: scan backwards for LDA #hi/PHA/LDA #lo/PHA.
                 * Works both when the pattern is at func_base (original case) and when it
                 * starts at a branch-target block entry within the function (e.g., $BAD9
                 * is a goto target inside an outer function, but func_base is the outer
                 * function start — the backward scan finds the inner block's push). */
                int has_outer_cont = 0;
                uint16_t outer_cont_target = 0;
                for (int _back = 6; _back <= 128; _back++) {
                    if (pc < (uint16_t)(0x8000 + _back + 5)) break;
                    uint16_t _probe = (uint16_t)(pc - _back);
                    if (rom_read(rom, bank, _probe)   == 0xA9 /* LDA #imm */ &&
                        rom_read(rom, bank, _probe+2) == 0x48 /* PHA */ &&
                        rom_read(rom, bank, _probe+3) == 0xA9 /* LDA #imm */ &&
                        rom_read(rom, bank, _probe+5) == 0x48 /* PHA */) {
                        uint8_t hi_val = rom_read(rom, bank, _probe+1);
                        uint8_t lo_val = rom_read(rom, bank, _probe+4);
                        uint16_t tgt = (uint16_t)(((uint16_t)hi_val << 8) | lo_val) + 1;
                        /* Outer continuations must be in the fixed bank ($C000+).
                         * Switchable-bank addresses are false positives — the bank
                         * may have changed by the time we'd return to them. */
                        if (tgt >= 0xC000 && tgt != (uint16_t)(pc + 1)) {
                            outer_cont_target = tgt;
                            has_outer_cont = 1;
                            break;
                        }
                    }
                }
                if (has_outer_cont) {
                    /* Pop inner handler, call it, discard outer cont bytes, call cont.
                     * The dispatched function's RTS consumes the caller's JSR push,
                     * so skip the standard RTS pop below. */
                    fprintf(f, "{ g_cpu.S++; uint8_t _lo=g_ram[0x100+g_cpu.S]; g_cpu.S++; uint8_t _hi=g_ram[0x100+g_cpu.S]; call_by_address(((uint16_t)_hi<<8|_lo)+1); g_cpu.S+=2; call_by_address(0x%04X); }\n    ", outer_cont_target);
                } else {
                    /* Pop pushed address, dispatch to computed target.
                     * The dispatched function's RTS consumes the caller's JSR push,
                     * so skip the standard RTS pop below. */
                    fprintf(f, "{ g_cpu.S++; uint8_t _lo=g_ram[0x100+g_cpu.S]; g_cpu.S++; uint8_t _hi=g_ram[0x100+g_cpu.S]; call_by_address(((uint16_t)_hi<<8|_lo)+1); }\n    ");
                }
                /* RTS-as-JMP: the dispatched function's own RTS pops the
                 * caller's JSR return from the 6502 stack. Don't double-pop. */
                goto rts_done;
            }
            if (cfg->push_all_jsr) {
                fprintf(f, "g_cpu.S += 2; /* pop JSR return address */\n");
            }
            rts_done:
            fprintf(f, "\n#ifdef RECOMP_STACK_TRACKING\n    recomp_stack_pop();\n#endif\n    return;\n");
            break;
        case MN_RTI: fprintf(f, "/* RTI */ g_cpu.S++; { uint8_t p=g_ram[0x100+g_cpu.S]; g_cpu.N=(p>>7)&1; g_cpu.V=(p>>6)&1; g_cpu.D=(p>>3)&1; g_cpu.I=(p>>2)&1; g_cpu.Z=(p>>1)&1; g_cpu.C=p&1; } g_cpu.S++; g_cpu.S++; /* pop PCL, PCH */\n#ifdef RECOMP_STACK_TRACKING\n    recomp_stack_pop();\n#endif\n    return;\n"); break;

        /* Flags */
        case MN_CLC: fprintf(f, "g_cpu.C = 0;\n"); break;
        case MN_SEC: fprintf(f, "g_cpu.C = 1;\n"); break;
        case MN_CLD: fprintf(f, "g_cpu.D = 0;\n"); break;
        case MN_SED: fprintf(f, "g_cpu.D = 1;\n"); break;
        case MN_CLI: fprintf(f, "g_cpu.I = 0;\n"); break;
        case MN_SEI: fprintf(f, "g_cpu.I = 1;\n"); break;
        case MN_CLV: fprintf(f, "g_cpu.V = 0;\n"); break;

        case MN_NOP: fprintf(f, "/* NOP */\n"); break;
        case MN_BRK: fprintf(f, "/* BRK — software interrupt, skip */\n"); break;

        default:
            fprintf(f, "/* unhandled mnemonic %d */\n", e->mnemonic);
            break;
    }

    return e->size;
}

/* Determine if an address is a branch target within this function's range */
static bool is_branch_target(const NESRom *rom, int bank,
                              uint16_t func_start, int func_size_bytes,
                              uint16_t addr) {
    /* Scan the function for branch instructions pointing to addr */
    uint16_t pc = func_start;
    int fixed = rom->prg_banks - 1;
    int scan_bank = (func_start >= 0xC000) ? fixed : bank;
    int bytes = 0;

    while (bytes < func_size_bytes && bytes < MAX_INSNS_PER_FUNC * 3) {
        uint8_t opcode = rom_read(rom, scan_bank, pc);
        const OpcodeEntry *e = &g_opcode_table[opcode];
        if (e->size == 0) break;

        /* Check if this is a branch */
        switch (e->mnemonic) {
            case MN_BCC: case MN_BCS: case MN_BEQ: case MN_BNE:
            case MN_BMI: case MN_BPL: case MN_BVC: case MN_BVS: {
                int8_t off = (int8_t)rom_read(rom, scan_bank, pc+1);
                uint16_t target = pc + 2 + off;
                if (target == addr) return true;
                break;
            }
            default: break;
        }
        pc += e->size;
        bytes += e->size;
    }
    return false;
}

/* Check if a function address+bank falls within an SRAM-to-ROM mapped region.
 * SRAM functions run from RAM and bank-switch during execution, so JSR calls
 * to the switchable bank range ($8000-$BFFF) must use dynamic dispatch. */
static int is_sram_sourced(const GameConfig *cfg, int bank, uint16_t addr) {
    for (int i = 0; i < cfg->sram_map_count; i++) {
        const SramMap *m = &cfg->sram_maps[i];
        if (bank == m->bank && addr >= m->rom_start && addr < m->rom_start + m->size)
            return 1;
    }
    return 0;
}

static int codegen_is_data_region(const GameConfig *cfg, int bank, uint16_t addr) {
    for (int i = 0; i < cfg->data_region_count; i++) {
        const DataRegion *dr = &cfg->data_regions[i];
        if ((dr->bank == bank || dr->bank == -1) &&
            addr >= dr->start && addr < dr->end)
            return 1;
    }
    return 0;
}

static void emit_function(FILE *f, const NESRom *rom, const FunctionEntry *fe,
                          const FunctionList *funcs, const AnnotationTable *at,
                          const GameConfig *cfg) {
    int fixed_bank = rom->prg_banks - 1;
    int bank = fe->bank;
    uint16_t pc = fe->addr;
    int sram_sourced = is_sram_sourced(cfg, bank, fe->addr);

    /* Skip functions marked as replace_func — their bodies are provided
     * by custom C implementations in extras.c. */
    for (int ri = 0; ri < cfg->replace_func_count; ri++) {
        int rb = (cfg->replace_funcs[ri].bank < 0) ? fixed_bank : cfg->replace_funcs[ri].bank;
        if (rb == bank && cfg->replace_funcs[ri].addr == pc) return;
    }

    /* Function-level annotation (appears before the signature) */
    const char *fann = annotation_lookup(at, bank, pc);
    if (fann) fprintf(f, "/* NOTE: %s */\n", fann);

    /* Pre-scan: collect all valid instruction-start addresses within this function.
     * Mimics the emission loop's stop logic (stops at RTS/JMP/RTI/BRK when no pending
     * forward branches remain). This prevents overrunning into neighboring functions. */
    uint16_t valid_starts[MAX_INSNS_PER_FUNC];
    int valid_count = 0;
    /* Collect merge partner addresses for this function */
    uint16_t merge_partners[256];
    int merge_partner_count = 0;
    for (int mi = 0; mi < cfg->merge_func_count; mi++) {
        if (cfg->merge_funcs[mi].bank != bank) continue;
        if (cfg->merge_funcs[mi].addr_lo == pc) {
            if (merge_partner_count < 256)
                merge_partners[merge_partner_count++] = cfg->merge_funcs[mi].addr_hi;
        }
    }
    /* Expand merge_range: if this function is the canonical (lowest) entry in
     * a merge_range, collect ALL other functions in the range as partners. */
    for (int ri = 0; ri < cfg->merge_range_count; ri++) {
        if (cfg->merge_ranges[ri].bank != bank) continue;
        if (pc < cfg->merge_ranges[ri].addr_lo || pc > cfg->merge_ranges[ri].addr_hi) continue;
        /* Find canonical (lowest) function entry in this range */
        uint16_t canonical = 0xFFFF;
        for (int fi = 0; fi < funcs->count; fi++) {
            uint16_t fa = funcs->entries[fi].addr;
            int fb = funcs->entries[fi].bank;
            if (fb != bank) continue;
            if (fa >= cfg->merge_ranges[ri].addr_lo && fa <= cfg->merge_ranges[ri].addr_hi) {
                if (fa < canonical) canonical = fa;
            }
        }
        if (pc != canonical) break; /* only canonical collects partners */
        /* Add all other functions in the range as merge partners */
        for (int fi = 0; fi < funcs->count; fi++) {
            uint16_t fa = funcs->entries[fi].addr;
            int fb = funcs->entries[fi].bank;
            if (fb != bank || fa == pc) continue;
            if (fa < cfg->merge_ranges[ri].addr_lo || fa > cfg->merge_ranges[ri].addr_hi) continue;
            /* Deduplicate */
            bool dup = false;
            for (int di = 0; di < merge_partner_count; di++)
                if (merge_partners[di] == fa) { dup = true; break; }
            if (!dup && merge_partner_count < 256)
                merge_partners[merge_partner_count++] = fa;
        }
        break;
    }

    {
        uint16_t scan = pc;
        uint16_t ps_pending[256];
        int ps_pending_count = 0;
        /* Seed pending list with merge partners so scanning includes their code */
        for (int mi = 0; mi < merge_partner_count; mi++) {
            ps_pending[ps_pending_count++] = merge_partners[mi];
        }
        for (int i = 0; i < MAX_INSNS_PER_FUNC; i++) {
            if (scan < 0x8000) break;
            /* Remove this address from ps_pending (we're visiting it now) */
            for (int p = 0; p < ps_pending_count; p++) {
                if (ps_pending[p] == scan) {
                    ps_pending[p] = ps_pending[--ps_pending_count];
                    break;
                }
            }
            valid_starts[valid_count++] = scan;
            uint8_t op = rom_read(rom, bank, scan);
            const OpcodeEntry *e2 = &g_opcode_table[op];
            int sz = (e2->size > 0) ? e2->size : 1;
            /* Trampoline / inline_dispatch JSR: may consume more than 3 bytes */
            if (e2->mnemonic == MN_JSR) {
                uint8_t _lo = rom_read(rom, bank, scan + 1);
                uint8_t _hi = rom_read(rom, bank, scan + 2);
                uint16_t _tgt = _lo | ((uint16_t)_hi << 8);
                for (int _ti = 0; _ti < cfg->trampoline_count; _ti++) {
                    if (_tgt == cfg->trampolines[_ti].addr) {
                        sz = 3 + cfg->trampolines[_ti].inline_bytes;
                        break;
                    }
                }
                for (int _ti = 0; _ti < cfg->inline_dispatch_count; _ti++) {
                    if (_tgt == cfg->inline_dispatches[_ti].addr) {
                        /* Count inline table bytes */
                        uint16_t _tpc = scan + 3;
                        while (rom_read(rom, bank, _tpc + 1) >= 0x80) _tpc += 2;
                        sz = (int)(_tpc - scan);
                        break;
                    }
                }
                for (int _ti = 0; _ti < cfg->inline_pointer_count; _ti++) {
                    if (_tgt == cfg->inline_pointers[_ti].addr) {
                        sz = 5;
                        break;
                    }
                }
                for (int _ti = 0; _ti < cfg->nop_jsr_count; _ti++) {
                    if (_tgt == cfg->nop_jsrs[_ti]) {
                        sz = 3; /* just the JSR, no inline data */
                        break;
                    }
                }
            }
            /* Track forward branch targets so we continue past early RTS/JMP */
            switch (e2->mnemonic) {
                case MN_BCC: case MN_BCS: case MN_BEQ: case MN_BNE:
                case MN_BMI: case MN_BPL: case MN_BVC: case MN_BVS: {
                    int8_t off = (int8_t)rom_read(rom, bank, scan + 1);
                    uint16_t tgt = scan + 2 + (int16_t)off;
                    if (tgt > scan && tgt >= pc && ps_pending_count < 256) {
                        bool found = false;
                        for (int p = 0; p < ps_pending_count; p++)
                            if (ps_pending[p] == tgt) { found = true; break; }
                        if (!found) ps_pending[ps_pending_count++] = tgt;
                    }
                    break;
                }
                default: break;
            }
            /* For JMP to merge partner: add target as pending (continue scan through it) */
            if (e2->mnemonic == MN_JMP && e2->addr_mode == AM_ABS) {
                uint8_t jmp_lo = rom_read(rom, bank, scan + 1);
                uint8_t jmp_hi = rom_read(rom, bank, scan + 2);
                uint16_t jmp_tgt = jmp_lo | ((uint16_t)jmp_hi << 8);
                for (int mi = 0; mi < merge_partner_count; mi++) {
                    if (jmp_tgt == merge_partners[mi] && ps_pending_count < 256) {
                        bool found = false;
                        for (int p = 0; p < ps_pending_count; p++)
                            if (ps_pending[p] == jmp_tgt) { found = true; break; }
                        if (!found) ps_pending[ps_pending_count++] = jmp_tgt;
                    }
                }
                /* Also add the function's own base as a merge partner target */
                if (jmp_tgt == pc && ps_pending_count < 256) {
                    bool found = false;
                    for (int p = 0; p < ps_pending_count; p++)
                        if (ps_pending[p] == jmp_tgt) { found = true; break; }
                    if (!found) ps_pending[ps_pending_count++] = jmp_tgt;
                }
            }
            if (e2->mnemonic == MN_ILLEGAL) { scan += sz; continue; }
            /* 4-PHA dispatch RTS: continuation (scan+1) must be included in scan */
            if (e2->mnemonic == MN_RTS && scan >= 0x800D &&
                rom_read(rom, bank, scan-1)  == 0x48 &&
                rom_read(rom, bank, scan-5)  == 0x48 &&
                rom_read(rom, bank, scan-9)  == 0x48 &&
                rom_read(rom, bank, scan-12) == 0x48) {
                uint16_t cont = scan + 1;
                bool found = false;
                for (int p = 0; p < ps_pending_count; p++)
                    if (ps_pending[p] == cont) { found = true; break; }
                if (!found && ps_pending_count < 256) ps_pending[ps_pending_count++] = cont;
            }
            /* Stop at terminal instructions when no pending forward branches */
            if (e2->mnemonic == MN_RTS || e2->mnemonic == MN_RTI ||
                e2->mnemonic == MN_BRK || e2->mnemonic == MN_JMP) {
                if (ps_pending_count == 0) break;
            }
            scan += sz;
        }
    }

    /* Detect secondary entry points (extra_label and merge_func addresses inside this function).
     * If any exist, emit a multi-entry _body function with goto dispatch. */
    uint16_t secondary_addrs[64];
    int secondary_count = 0;
    for (int li = 0; li < cfg->extra_label_count && secondary_count < 64; li++) {
        int lbl_bank = cfg->extra_labels[li].bank;
        uint16_t lbl_addr = cfg->extra_labels[li].addr;
        if (lbl_bank != bank) continue;
        if (lbl_addr == pc) continue; /* same as function start */
        /* Skip if this address already has its own function (standalone) */
        if (function_list_contains(funcs, lbl_addr, bank)) continue;
        for (int v = 0; v < valid_count; v++) {
            if (valid_starts[v] == lbl_addr) {
                secondary_addrs[secondary_count++] = lbl_addr;
                break;
            }
        }
    }
    /* Add merge_func/merge_range partners as secondary entries.
     * Only add if the address is on a valid instruction boundary (in valid_starts).
     * Overlapping mid-instruction entries (common in 6502 code) get different
     * instruction streams and must remain as independent functions. */
    for (int mi = 0; mi < merge_partner_count && secondary_count < 64; mi++) {
        uint16_t mp = merge_partners[mi];
        bool found = false;
        for (int si = 0; si < secondary_count; si++)
            if (secondary_addrs[si] == mp) { found = true; break; }
        if (!found) {
            bool valid = false;
            for (int v = 0; v < valid_count; v++)
                if (valid_starts[v] == mp) { valid = true; break; }
            if (valid)
                secondary_addrs[secondary_count++] = mp;
        }
    }

    int is_multi_entry = (secondary_count > 0);

    /* Emit function signature — for multi-entry, emit a static _body function */
    if (is_multi_entry) {
        if (bank == fixed_bank && pc >= 0xC000) {
            fprintf(f, "static void func_%04X_body(int _entry) {\n", pc);
        } else {
            fprintf(f, "static void func_%04X_b%d_body(int _entry) {\n", pc, bank);
        }
        /* Entry dispatch — jump to secondary entry label */
        fprintf(f, "    switch (_entry) {\n");
        for (int si = 0; si < secondary_count; si++) {
            fprintf(f, "        case %d: goto label_%04X;\n", si + 1, secondary_addrs[si]);
        }
        fprintf(f, "    }\n");
    } else {
        if (bank == fixed_bank && pc >= 0xC000) {
            fprintf(f, "void func_%04X(void) {\n", pc);
            fprintf(f, "#ifdef RECOMP_STACK_TRACKING\n");
            fprintf(f, "    recomp_stack_push(\"func_%04X\");\n", pc);
            fprintf(f, "#endif\n");
        } else {
            fprintf(f, "void func_%04X_b%d(void) {\n", pc, bank);
            fprintf(f, "#ifdef RECOMP_STACK_TRACKING\n");
            fprintf(f, "    recomp_stack_push(\"func_%04X_b%d\");\n", pc, bank);
            fprintf(f, "#endif\n");
        }
    }

    /* Pending forward branch targets — branches that jump past a RTS/JMP.
     * We continue emitting after the stop instruction until all pending are covered.
     * Seed with merge partners so emission continues through their code. */
    uint16_t pending[256];
    int pending_count = 0;
    for (int mi = 0; mi < merge_partner_count && pending_count < 256; mi++) {
        pending[pending_count++] = merge_partners[mi];
    }
    /* Branch-target set: RTS addresses that are direct branch targets bypass PHA setup;
     * they must be emitted as regular returns, not 2-PHA dispatches. */
    uint16_t branch_targets[256];
    int branch_targets_count = 0;
    int pending_pha_count = 0; /* net PHAs pushed without matching PLA (for non-adjacent dispatch) */

    /* Track addresses emitted as labels in this function, so JMP can use goto
     * for backward jumps within the function body (avoiding mutual tail-call recursion). */
    uint16_t emitted_addrs[MAX_INSNS_PER_FUNC];
    int emitted_count = 0;

    /* Coroutine scheduler detection: if we see LDX #$FF; TXS (stack reset to $FF),
     * this function contains a scheduler loop. Record the LDX address so that
     * coroutine START (JMP ind) and RESUME (RTS after TXS) can goto it. */
    uint16_t sched_reset_addr = 0;

    /* effective_bank is passed to emit_instruction for inline_dispatch resolution.
     * For switchable-bank functions, effective_bank == bank.
     * For fixed-bank functions, each inline_dispatch does its own backward scan. */
    int effective_bank = bank;

    uint16_t cursor = pc;
    for (int insn = 0; insn < MAX_INSNS_PER_FUNC; insn++) {
        fprintf(f, "label_%04X:;\n", cursor);
        if (emitted_count < MAX_INSNS_PER_FUNC)
            emitted_addrs[emitted_count++] = cursor;

        /* Instruction-level annotation (skipped at function start — already shown above) */
        if (cursor != pc) {
            const char *iann = annotation_lookup(at, bank, cursor);
            if (iann) fprintf(f, "    /* NOTE: %s */\n", iann);
        }

        /* Remove this address from pending (we're emitting it now) */
        for (int p = 0; p < pending_count; p++) {
            if (pending[p] == cursor) {
                pending[p] = pending[--pending_count];
                break;
            }
        }

        uint8_t opcode = rom_read(rom, bank, cursor);
        const OpcodeEntry *e = &g_opcode_table[opcode];

        /* Track forward branch targets (only non-cross-function ones go into pending) */
        switch (e->mnemonic) {
            case MN_BCC: case MN_BCS: case MN_BEQ: case MN_BNE:
            case MN_BMI: case MN_BPL: case MN_BVC: case MN_BVS: {
                int8_t off = (int8_t)rom_read(rom, bank, cursor + 1);
                uint16_t tgt = cursor + 2 + off;
                /* Only track as pending if it's a local forward target
                 * (not a cross-function branch — those get tail-call treatment) */
                if (tgt > cursor && tgt >= pc
                        && is_valid_label_target(tgt, valid_starts, valid_count, rom, bank)
                        && pending_count < 256) {
                    /* Check not already in pending */
                    bool found = false;
                    for (int p = 0; p < pending_count; p++)
                        if (pending[p] == tgt) { found = true; break; }
                    if (!found) pending[pending_count++] = tgt;
                    /* Record as branch target: RTS at tgt would bypass any PHA setup */
                    bool bt_found = false;
                    for (int b = 0; b < branch_targets_count; b++)
                        if (branch_targets[b] == tgt) { bt_found = true; break; }
                    if (!bt_found && branch_targets_count < 256) branch_targets[branch_targets_count++] = tgt;
                }
                break;
            }
            default: break;
        }

        /* 4-PHA dispatch RTS: add cont (cursor+1) to pending so emit loop continues */
        if (e->mnemonic == MN_RTS && cursor >= 0x800D &&
            rom_read(rom, bank, cursor-1)  == 0x48 &&
            rom_read(rom, bank, cursor-5)  == 0x48 &&
            rom_read(rom, bank, cursor-9)  == 0x48 &&
            rom_read(rom, bank, cursor-12) == 0x48) {
            uint16_t cont = cursor + 1;
            bool found = false;
            for (int p = 0; p < pending_count; p++)
                if (pending[p] == cont) { found = true; break; }
            if (!found && pending_count < 256) pending[pending_count++] = cont;
        }

        /* If this RTS is a direct branch target, the PHA setup was bypassed —
         * emit a regular return instead of a 2-PHA dispatch. */
        if (e->mnemonic == MN_RTS && cursor >= 0x8001 &&
            rom_read(rom, bank, cursor - 1) == 0x48) {
            bool is_branch_tgt = false;
            for (int b = 0; b < branch_targets_count; b++)
                if (branch_targets[b] == cursor) { is_branch_tgt = true; break; }
            if (is_branch_tgt) {
                fprintf(f, "    /* $%04X: 60 */\n", cursor);
                if (cfg->push_all_jsr) fprintf(f, "    g_cpu.S += 2; /* pop JSR return address */\n");
                fprintf(f, "#ifdef RECOMP_STACK_TRACKING\n    recomp_stack_pop();\n#endif\n    return; /* branch-target RTS */\n");
                if (pending_count == 0) break;
                cursor += 1;
                continue;
            }
        }

        /* Detect coroutine scheduler stack reset: LDX #$FF ($A2 $FF) followed by
         * TXS ($9A). When found, record the LDX address as the scheduler loop entry. */
        if (rom_read(rom, bank, cursor) == 0x9A /* TXS */ &&
            cursor >= 2 &&
            rom_read(rom, bank, cursor - 2) == 0xA2 /* LDX #imm */ &&
            rom_read(rom, bank, cursor - 1) == 0xFF) {
            sched_reset_addr = cursor - 2;
        }

        int consumed = emit_instruction(f, rom, bank, cursor, pc, fixed_bank, funcs,
                                        valid_starts, valid_count, cfg, sram_sourced,
                                        effective_bank,
                                        merge_partners, merge_partner_count,
                                        emitted_addrs, emitted_count,
                                        sched_reset_addr);

        /* If this PHA is immediately followed by a branch-target RTS, the fall-through path
         * must dispatch now (before reaching the RTS label, which is bypassed by branches).
         * Emit the 2-PHA dispatch inline and return; the branch path will hit label_RTS: return. */
        if (e->mnemonic == MN_PHA) {
            uint16_t next = cursor + 1;
            if (next >= 0x8001 && rom_read(rom, bank, next) == 0x60) {
                bool is_branch_tgt = false;
                for (int b = 0; b < branch_targets_count; b++)
                    if (branch_targets[b] == next) { is_branch_tgt = true; break; }
                if (is_branch_tgt) {
                    fprintf(f, "    { g_cpu.S++; uint8_t _lo=g_ram[0x100+g_cpu.S]; g_cpu.S++; uint8_t _hi=g_ram[0x100+g_cpu.S]; call_by_address(((uint16_t)_hi<<8|_lo)+1); }\n");
                    fprintf(f, "    return;\n");
                }
            }
        }

        /* Update net PHA count for non-adjacent dispatch detection */
        if (e->mnemonic == MN_PHA) pending_pha_count++;
        else if (e->mnemonic == MN_PLA && pending_pha_count > 0) pending_pha_count--;

        /* Non-adjacent 2-PHA dispatch: if the NEXT instruction is a branch-target RTS and
         * 2 PHAs have been pushed earlier in this function without matching PLAs, emit the
         * dispatch inline here (fall-through path). The RTS label handles branch paths.
         * Example: $AC2D/$AC70 — PHA/PHA/LDY $00 / RTS(branch-target). */
        if (e->mnemonic != MN_PHA && pending_pha_count >= 2) {
            uint16_t _nxt = (uint16_t)(cursor + consumed);
            if (_nxt >= 0x8001 && rom_read(rom, bank, _nxt) == 0x60 /* RTS */) {
                bool _is_bt = false;
                for (int _b = 0; _b < branch_targets_count; _b++)
                    if (branch_targets[_b] == _nxt) { _is_bt = true; break; }
                if (_is_bt) {
                    fprintf(f, "    { g_cpu.S++; uint8_t _lo=g_ram[0x100+g_cpu.S]; g_cpu.S++; uint8_t _hi=g_ram[0x100+g_cpu.S]; call_by_address(((uint16_t)_hi<<8|_lo)+1); }\n");
                    fprintf(f, "    return;\n");
                }
            }
        }

        /* Check stop conditions — only stop if no pending forward targets remain */
        if (e->mnemonic == MN_RTS || e->mnemonic == MN_RTI || e->mnemonic == MN_BRK) {
            if (pending_count == 0) break;
            /* pending targets exist — continue emitting (reached only via goto) */
            cursor += consumed;
            continue;
        }
        if (e->mnemonic == MN_JMP) {
            if (pending_count == 0) break;
            cursor += consumed;
            continue;
        }

        cursor += consumed;
    }

    fprintf(f, "}\n\n");

    /* For multi-entry functions, emit thin wrappers after the body */
    if (is_multi_entry) {
        /* Primary entry wrapper */
        if (bank == fixed_bank && pc >= 0xC000) {
            fprintf(f, "void func_%04X(void) {\n", pc);
            fprintf(f, "#ifdef RECOMP_STACK_TRACKING\n");
            fprintf(f, "    recomp_stack_push(\"func_%04X\");\n", pc);
            fprintf(f, "#endif\n");
            fprintf(f, "    func_%04X_body(0);\n", pc);
            fprintf(f, "#ifdef RECOMP_STACK_TRACKING\n");
            fprintf(f, "    recomp_stack_pop();\n");
            fprintf(f, "#endif\n");
            fprintf(f, "}\n\n");
        } else {
            fprintf(f, "void func_%04X_b%d(void) {\n", pc, bank);
            fprintf(f, "#ifdef RECOMP_STACK_TRACKING\n");
            fprintf(f, "    recomp_stack_push(\"func_%04X_b%d\");\n", pc, bank);
            fprintf(f, "#endif\n");
            fprintf(f, "    func_%04X_b%d_body(0);\n", pc, bank);
            fprintf(f, "#ifdef RECOMP_STACK_TRACKING\n");
            fprintf(f, "    recomp_stack_pop();\n");
            fprintf(f, "#endif\n");
            fprintf(f, "}\n\n");
        }
        /* Secondary entry wrappers */
        for (int si = 0; si < secondary_count; si++) {
            uint16_t sa = secondary_addrs[si];
            if (bank == fixed_bank && sa >= 0xC000) {
                fprintf(f, "void func_%04X(void) {\n", sa);
                fprintf(f, "#ifdef RECOMP_STACK_TRACKING\n");
                fprintf(f, "    recomp_stack_push(\"func_%04X\");\n", sa);
                fprintf(f, "#endif\n");
                fprintf(f, "    func_%04X_body(%d);\n", pc, si + 1);
                fprintf(f, "#ifdef RECOMP_STACK_TRACKING\n");
                fprintf(f, "    recomp_stack_pop();\n");
                fprintf(f, "#endif\n");
                fprintf(f, "}\n\n");
            } else {
                fprintf(f, "void func_%04X_b%d(void) {\n", sa, bank);
                fprintf(f, "#ifdef RECOMP_STACK_TRACKING\n");
                fprintf(f, "    recomp_stack_push(\"func_%04X_b%d\");\n", sa, bank);
                fprintf(f, "#endif\n");
                fprintf(f, "    func_%04X_b%d_body(%d);\n", pc, bank, si + 1);
                fprintf(f, "#ifdef RECOMP_STACK_TRACKING\n");
                fprintf(f, "    recomp_stack_pop();\n");
                fprintf(f, "#endif\n");
                fprintf(f, "}\n\n");
            }
        }
    }
}

/* Emit dispatch table */
static void emit_dispatch(FILE *f, const FunctionList *funcs, const NESRom *rom,
                          const GameConfig *cfg) {
    int fixed_bank = rom->prg_banks - 1;

    fprintf(f,
        "/* AUTO-GENERATED dispatch table. DO NOT EDIT. */\n"
        "#include \"nes_runtime.h\"\n"
        "extern int g_current_bank;\n\n"
        "int call_by_address(uint16_t addr) {\n"
        "    switch (addr) {\n"
    );

    /* Emit one case per unique address. For addresses with multiple bank
     * variants (switchable banks), emit an inner switch on g_current_bank. */
    for (int i = 0; i < funcs->count; i++) {
        uint16_t addr = funcs->entries[i].addr;

        /* Skip if already emitted (seen earlier in the list) */
        bool already = false;
        for (int j = 0; j < i; j++)
            if (funcs->entries[j].addr == addr) { already = true; break; }
        if (already) continue;

        /* Collect all bank variants for this address */
        int variants[32];
        int nv = 0;
        for (int j = i; j < funcs->count && nv < 32; j++)
            if (funcs->entries[j].addr == addr)
                variants[nv++] = funcs->entries[j].bank;

        fprintf(f, "        case 0x%04X:\n", addr);

        if (nv == 1) {
            int bk = variants[0];
            if (bk == fixed_bank && addr >= 0xC000) {
                fprintf(f, "            func_%04X(); break;\n", addr);
            } else {
                fprintf(f, "            func_%04X_b%d(); break;\n", addr, bk);
            }
        } else {
            /* Multiple bank variants: dispatch by current bank */
            fprintf(f, "            switch (g_current_bank) {\n");

            /* Check if bank 15 (fixed) is already a variant. If not, and if the
             * fixed-bank equivalent (addr + $4000) exists, add a bank-15 alias.
             * This handles the case where the game maps bank15 into the switchable
             * slot ($8000-$BFFF) and calls switchable addresses that alias to
             * fixed-bank functions (switchable $XXXX = fixed $XXXX+$4000). */
            bool has_fb15 = false;
            for (int v = 0; v < nv; v++)
                if (variants[v] == fixed_bank) { has_fb15 = true; break; }
            if (!has_fb15 && addr >= 0x8000 && addr <= 0xBFFF) {
                uint16_t fb_equiv = addr + 0x4000;
                if (function_list_contains(funcs, fb_equiv, fixed_bank))
                    fprintf(f, "                case %d: func_%04X(); break;\n",
                            fixed_bank, fb_equiv);
            }

            bool has_default = false;
            for (int v = 0; v < nv; v++) {
                int bk = variants[v];
                if (bk == fixed_bank && addr >= 0xC000) {
                    fprintf(f, "                default: func_%04X(); break;\n", addr);
                    has_default = true;
                } else
                    fprintf(f, "                case %d: func_%04X_b%d(); break;\n",
                            bk, addr, bk);
            }
            if (!has_default)
                fprintf(f, "                default: nes_log_dispatch_miss(addr); return 0;\n");
            fprintf(f, "            }\n");
            fprintf(f, "            break;\n");
        }
    }

    /* Extra_label secondary entries — add dispatch cases for their ROM addresses */
    if (cfg) {
        for (int i = 0; i < cfg->extra_label_count; i++) {
            uint16_t addr = cfg->extra_labels[i].addr;
            int bk = cfg->extra_labels[i].bank;
            /* Skip if any function at this address already has a case */
            bool has_case = false;
            for (int j = 0; j < funcs->count; j++)
                if (funcs->entries[j].addr == addr) { has_case = true; break; }
            if (has_case) continue;
            fprintf(f, "        case 0x%04X:\n", addr);
            if (bk == fixed_bank && addr >= 0xC000)
                fprintf(f, "            func_%04X(); break;\n", addr);
            else
                fprintf(f, "            func_%04X_b%d(); break;\n", addr, bk);
        }
    }

    fprintf(f,
        "        default:\n"
        "            nes_log_dispatch_miss(addr);\n"
        "            return 0;\n"
        "    }\n"
        "    return 1;\n"
        "}\n"
    );
}

bool codegen_emit(const NESRom *rom, const FunctionList *funcs,
                  const char *out_full_path, const char *out_dispatch_path,
                  const AnnotationTable *at, const GameConfig *cfg) {
    FILE *f_full = fopen(out_full_path, "w");
    if (!f_full) {
        fprintf(stderr, "codegen: cannot open %s\n", out_full_path);
        return false;
    }

    emit_header(f_full);
    emit_forward_decls(f_full, funcs, rom, cfg);

    int fixed_bank = rom->prg_banks - 1;
    for (int i = 0; i < funcs->count; i++) {
        /* Skip merge_func addr_hi entries — they're generated as part of addr_lo's body */
        bool is_merge_hi = false;
        for (int mi = 0; mi < cfg->merge_func_count; mi++) {
            if (funcs->entries[i].bank == cfg->merge_funcs[mi].bank &&
                funcs->entries[i].addr == cfg->merge_funcs[mi].addr_hi) {
                is_merge_hi = true;
                break;
            }
        }
        if (is_merge_hi) continue;
        /* Skip merge_range non-canonical entries — but only if they were
         * actually emitted as secondary labels in the canonical function's body.
         * Overlapping mid-instruction entries can't be merged and must be
         * emitted as independent functions. */
        bool is_range_secondary = false;
        for (int ri = 0; ri < cfg->merge_range_count && !is_range_secondary; ri++) {
            if (funcs->entries[i].bank != cfg->merge_ranges[ri].bank) continue;
            uint16_t fa = funcs->entries[i].addr;
            if (fa < cfg->merge_ranges[ri].addr_lo || fa > cfg->merge_ranges[ri].addr_hi) continue;
            uint16_t canonical = 0xFFFF;
            for (int fi = 0; fi < funcs->count; fi++) {
                if (funcs->entries[fi].bank != cfg->merge_ranges[ri].bank) continue;
                uint16_t ca = funcs->entries[fi].addr;
                if (ca >= cfg->merge_ranges[ri].addr_lo && ca <= cfg->merge_ranges[ri].addr_hi) {
                    if (ca < canonical) canonical = ca;
                }
            }
            if (fa == canonical) break; /* canonical is not secondary */
            /* Check if the canonical function's pre-scan covers this address
             * by doing a quick instruction walk from canonical to see if fa
             * falls on an instruction boundary. */
            uint16_t walk = canonical;
            int bank_for_walk = funcs->entries[i].bank;
            for (int wi = 0; wi < 512; wi++) {
                if (walk == fa) { is_range_secondary = true; break; }
                if (walk > fa || walk > cfg->merge_ranges[ri].addr_hi) break;
                uint8_t op = rom_read(rom, bank_for_walk, walk);
                extern const OpcodeEntry g_opcode_table[];
                const OpcodeEntry *ew = &g_opcode_table[op];
                int wsz = (ew->size > 0) ? ew->size : 1;
                walk += wsz;
            }
        }
        if (is_range_secondary) continue;

        emit_function(f_full, rom, &funcs->entries[i], funcs, at, cfg);
    }

    /* Add NMI/RESET/IRQ entry points for runner.
     * If the vector target is in the switchable bank ($8000-$BFFF), use _b0 suffix. */
    fprintf(f_full, "/* Runner entry points */\n");
    const char *reset_sfx = (rom->reset_vector < 0xC000) ? "_b0" : "";
    const char *nmi_sfx   = (rom->nmi_vector   < 0xC000) ? "_b0" : "";
    const char *irq_sfx   = (rom->irq_vector   < 0xC000) ? "_b0" : "";
    fprintf(f_full, "void func_RESET(void) { func_%04X%s(); }\n", rom->reset_vector, reset_sfx);
    fprintf(f_full, "void func_NMI(void)   { func_%04X%s(); }\n", rom->nmi_vector,   nmi_sfx);
    fprintf(f_full, "void func_IRQ(void)   { func_%04X%s(); }\n", rom->irq_vector,   irq_sfx);

    fclose(f_full);

    /* Dispatch table */
    FILE *f_disp = fopen(out_dispatch_path, "w");
    if (!f_disp) {
        fprintf(stderr, "codegen: cannot open %s\n", out_dispatch_path);
        return false;
    }
    emit_dispatch(f_disp, funcs, rom, cfg);
    fclose(f_disp);

    return true;
}
