/*
 * cpu6502_decoder.c — 256-entry 6502 opcode table
 * Valid 6502 has ~151 opcodes across 13 addressing modes.
 * Illegal opcodes marked MN_ILLEGAL (treated as 1-byte NOP in codegen).
 */
#include "cpu6502_decoder.h"

#define ILL {MN_ILLEGAL, AM_IMP, 1}

const OpcodeEntry g_opcode_table[256] = {
    /* 0x00 */ {MN_BRK, AM_IMP, 1},
    /* 0x01 */ {MN_ORA, AM_INDX, 2},
    /* 0x02 */ ILL,
    /* 0x03 */ ILL,
    /* 0x04 */ ILL,
    /* 0x05 */ {MN_ORA, AM_ZP, 2},
    /* 0x06 */ {MN_ASL, AM_ZP, 2},
    /* 0x07 */ ILL,
    /* 0x08 */ {MN_PHP, AM_IMP, 1},
    /* 0x09 */ {MN_ORA, AM_IMM, 2},
    /* 0x0A */ {MN_ASL, AM_ACC, 1},
    /* 0x0B */ ILL,
    /* 0x0C */ ILL,
    /* 0x0D */ {MN_ORA, AM_ABS, 3},
    /* 0x0E */ {MN_ASL, AM_ABS, 3},
    /* 0x0F */ ILL,
    /* 0x10 */ {MN_BPL, AM_REL, 2},
    /* 0x11 */ {MN_ORA, AM_INDY, 2},
    /* 0x12 */ ILL,
    /* 0x13 */ ILL,
    /* 0x14 */ ILL,
    /* 0x15 */ {MN_ORA, AM_ZPX, 2},
    /* 0x16 */ {MN_ASL, AM_ZPX, 2},
    /* 0x17 */ ILL,
    /* 0x18 */ {MN_CLC, AM_IMP, 1},
    /* 0x19 */ {MN_ORA, AM_ABSY, 3},
    /* 0x1A */ ILL,
    /* 0x1B */ ILL,
    /* 0x1C */ ILL,
    /* 0x1D */ {MN_ORA, AM_ABSX, 3},
    /* 0x1E */ {MN_ASL, AM_ABSX, 3},
    /* 0x1F */ ILL,
    /* 0x20 */ {MN_JSR, AM_ABS, 3},
    /* 0x21 */ {MN_AND, AM_INDX, 2},
    /* 0x22 */ ILL,
    /* 0x23 */ ILL,
    /* 0x24 */ {MN_BIT, AM_ZP, 2},
    /* 0x25 */ {MN_AND, AM_ZP, 2},
    /* 0x26 */ {MN_ROL, AM_ZP, 2},
    /* 0x27 */ ILL,
    /* 0x28 */ {MN_PLP, AM_IMP, 1},
    /* 0x29 */ {MN_AND, AM_IMM, 2},
    /* 0x2A */ {MN_ROL, AM_ACC, 1},
    /* 0x2B */ ILL,
    /* 0x2C */ {MN_BIT, AM_ABS, 3},
    /* 0x2D */ {MN_AND, AM_ABS, 3},
    /* 0x2E */ {MN_ROL, AM_ABS, 3},
    /* 0x2F */ ILL,
    /* 0x30 */ {MN_BMI, AM_REL, 2},
    /* 0x31 */ {MN_AND, AM_INDY, 2},
    /* 0x32 */ ILL,
    /* 0x33 */ ILL,
    /* 0x34 */ ILL,
    /* 0x35 */ {MN_AND, AM_ZPX, 2},
    /* 0x36 */ {MN_ROL, AM_ZPX, 2},
    /* 0x37 */ ILL,
    /* 0x38 */ {MN_SEC, AM_IMP, 1},
    /* 0x39 */ {MN_AND, AM_ABSY, 3},
    /* 0x3A */ ILL,
    /* 0x3B */ ILL,
    /* 0x3C */ ILL,
    /* 0x3D */ {MN_AND, AM_ABSX, 3},
    /* 0x3E */ {MN_ROL, AM_ABSX, 3},
    /* 0x3F */ ILL,
    /* 0x40 */ {MN_RTI, AM_IMP, 1},
    /* 0x41 */ {MN_EOR, AM_INDX, 2},
    /* 0x42 */ ILL,
    /* 0x43 */ ILL,
    /* 0x44 */ ILL,
    /* 0x45 */ {MN_EOR, AM_ZP, 2},
    /* 0x46 */ {MN_LSR, AM_ZP, 2},
    /* 0x47 */ ILL,
    /* 0x48 */ {MN_PHA, AM_IMP, 1},
    /* 0x49 */ {MN_EOR, AM_IMM, 2},
    /* 0x4A */ {MN_LSR, AM_ACC, 1},
    /* 0x4B */ ILL,
    /* 0x4C */ {MN_JMP, AM_ABS, 3},
    /* 0x4D */ {MN_EOR, AM_ABS, 3},
    /* 0x4E */ {MN_LSR, AM_ABS, 3},
    /* 0x4F */ ILL,
    /* 0x50 */ {MN_BVC, AM_REL, 2},
    /* 0x51 */ {MN_EOR, AM_INDY, 2},
    /* 0x52 */ ILL,
    /* 0x53 */ ILL,
    /* 0x54 */ ILL,
    /* 0x55 */ {MN_EOR, AM_ZPX, 2},
    /* 0x56 */ {MN_LSR, AM_ZPX, 2},
    /* 0x57 */ ILL,
    /* 0x58 */ {MN_CLI, AM_IMP, 1},
    /* 0x59 */ {MN_EOR, AM_ABSY, 3},
    /* 0x5A */ ILL,
    /* 0x5B */ ILL,
    /* 0x5C */ ILL,
    /* 0x5D */ {MN_EOR, AM_ABSX, 3},
    /* 0x5E */ {MN_LSR, AM_ABSX, 3},
    /* 0x5F */ ILL,
    /* 0x60 */ {MN_RTS, AM_IMP, 1},
    /* 0x61 */ {MN_ADC, AM_INDX, 2},
    /* 0x62 */ ILL,
    /* 0x63 */ ILL,
    /* 0x64 */ ILL,
    /* 0x65 */ {MN_ADC, AM_ZP, 2},
    /* 0x66 */ {MN_ROR, AM_ZP, 2},
    /* 0x67 */ ILL,
    /* 0x68 */ {MN_PLA, AM_IMP, 1},
    /* 0x69 */ {MN_ADC, AM_IMM, 2},
    /* 0x6A */ {MN_ROR, AM_ACC, 1},
    /* 0x6B */ ILL,
    /* 0x6C */ {MN_JMP, AM_IND, 3},
    /* 0x6D */ {MN_ADC, AM_ABS, 3},
    /* 0x6E */ {MN_ROR, AM_ABS, 3},
    /* 0x6F */ ILL,
    /* 0x70 */ {MN_BVS, AM_REL, 2},
    /* 0x71 */ {MN_ADC, AM_INDY, 2},
    /* 0x72 */ ILL,
    /* 0x73 */ ILL,
    /* 0x74 */ ILL,
    /* 0x75 */ {MN_ADC, AM_ZPX, 2},
    /* 0x76 */ {MN_ROR, AM_ZPX, 2},
    /* 0x77 */ ILL,
    /* 0x78 */ {MN_SEI, AM_IMP, 1},
    /* 0x79 */ {MN_ADC, AM_ABSY, 3},
    /* 0x7A */ ILL,
    /* 0x7B */ ILL,
    /* 0x7C */ ILL,
    /* 0x7D */ {MN_ADC, AM_ABSX, 3},
    /* 0x7E */ {MN_ROR, AM_ABSX, 3},
    /* 0x7F */ ILL,
    /* 0x80 */ ILL,
    /* 0x81 */ {MN_STA, AM_INDX, 2},
    /* 0x82 */ ILL,
    /* 0x83 */ ILL,
    /* 0x84 */ {MN_STY, AM_ZP, 2},
    /* 0x85 */ {MN_STA, AM_ZP, 2},
    /* 0x86 */ {MN_STX, AM_ZP, 2},
    /* 0x87 */ ILL,
    /* 0x88 */ {MN_DEY, AM_IMP, 1},
    /* 0x89 */ ILL,
    /* 0x8A */ {MN_TXA, AM_IMP, 1},
    /* 0x8B */ ILL,
    /* 0x8C */ {MN_STY, AM_ABS, 3},
    /* 0x8D */ {MN_STA, AM_ABS, 3},
    /* 0x8E */ {MN_STX, AM_ABS, 3},
    /* 0x8F */ ILL,
    /* 0x90 */ {MN_BCC, AM_REL, 2},
    /* 0x91 */ {MN_STA, AM_INDY, 2},
    /* 0x92 */ ILL,
    /* 0x93 */ ILL,
    /* 0x94 */ {MN_STY, AM_ZPX, 2},
    /* 0x95 */ {MN_STA, AM_ZPX, 2},
    /* 0x96 */ {MN_STX, AM_ZPY, 2},
    /* 0x97 */ ILL,
    /* 0x98 */ {MN_TYA, AM_IMP, 1},
    /* 0x99 */ {MN_STA, AM_ABSY, 3},
    /* 0x9A */ {MN_TXS, AM_IMP, 1},
    /* 0x9B */ ILL,
    /* 0x9C */ ILL,
    /* 0x9D */ {MN_STA, AM_ABSX, 3},
    /* 0x9E */ ILL,
    /* 0x9F */ ILL,
    /* 0xA0 */ {MN_LDY, AM_IMM, 2},
    /* 0xA1 */ {MN_LDA, AM_INDX, 2},
    /* 0xA2 */ {MN_LDX, AM_IMM, 2},
    /* 0xA3 */ ILL,
    /* 0xA4 */ {MN_LDY, AM_ZP, 2},
    /* 0xA5 */ {MN_LDA, AM_ZP, 2},
    /* 0xA6 */ {MN_LDX, AM_ZP, 2},
    /* 0xA7 */ ILL,
    /* 0xA8 */ {MN_TAY, AM_IMP, 1},
    /* 0xA9 */ {MN_LDA, AM_IMM, 2},
    /* 0xAA */ {MN_TAX, AM_IMP, 1},
    /* 0xAB */ ILL,
    /* 0xAC */ {MN_LDY, AM_ABS, 3},
    /* 0xAD */ {MN_LDA, AM_ABS, 3},
    /* 0xAE */ {MN_LDX, AM_ABS, 3},
    /* 0xAF */ ILL,
    /* 0xB0 */ {MN_BCS, AM_REL, 2},
    /* 0xB1 */ {MN_LDA, AM_INDY, 2},
    /* 0xB2 */ ILL,
    /* 0xB3 */ ILL,
    /* 0xB4 */ {MN_LDY, AM_ZPX, 2},
    /* 0xB5 */ {MN_LDA, AM_ZPX, 2},
    /* 0xB6 */ {MN_LDX, AM_ZPY, 2},
    /* 0xB7 */ ILL,
    /* 0xB8 */ {MN_CLV, AM_IMP, 1},
    /* 0xB9 */ {MN_LDA, AM_ABSY, 3},
    /* 0xBA */ {MN_TSX, AM_IMP, 1},
    /* 0xBB */ ILL,
    /* 0xBC */ {MN_LDY, AM_ABSX, 3},
    /* 0xBD */ {MN_LDA, AM_ABSX, 3},
    /* 0xBE */ {MN_LDX, AM_ABSY, 3},
    /* 0xBF */ ILL,
    /* 0xC0 */ {MN_CPY, AM_IMM, 2},
    /* 0xC1 */ {MN_CMP, AM_INDX, 2},
    /* 0xC2 */ ILL,
    /* 0xC3 */ ILL,
    /* 0xC4 */ {MN_CPY, AM_ZP, 2},
    /* 0xC5 */ {MN_CMP, AM_ZP, 2},
    /* 0xC6 */ {MN_DEC, AM_ZP, 2},
    /* 0xC7 */ ILL,
    /* 0xC8 */ {MN_INY, AM_IMP, 1},
    /* 0xC9 */ {MN_CMP, AM_IMM, 2},
    /* 0xCA */ {MN_DEX, AM_IMP, 1},
    /* 0xCB */ ILL,
    /* 0xCC */ {MN_CPY, AM_ABS, 3},
    /* 0xCD */ {MN_CMP, AM_ABS, 3},
    /* 0xCE */ {MN_DEC, AM_ABS, 3},
    /* 0xCF */ ILL,
    /* 0xD0 */ {MN_BNE, AM_REL, 2},
    /* 0xD1 */ {MN_CMP, AM_INDY, 2},
    /* 0xD2 */ ILL,
    /* 0xD3 */ ILL,
    /* 0xD4 */ ILL,
    /* 0xD5 */ {MN_CMP, AM_ZPX, 2},
    /* 0xD6 */ {MN_DEC, AM_ZPX, 2},
    /* 0xD7 */ ILL,
    /* 0xD8 */ {MN_CLD, AM_IMP, 1},
    /* 0xD9 */ {MN_CMP, AM_ABSY, 3},
    /* 0xDA */ ILL,
    /* 0xDB */ ILL,
    /* 0xDC */ ILL,
    /* 0xDD */ {MN_CMP, AM_ABSX, 3},
    /* 0xDE */ {MN_DEC, AM_ABSX, 3},
    /* 0xDF */ ILL,
    /* 0xE0 */ {MN_CPX, AM_IMM, 2},
    /* 0xE1 */ {MN_SBC, AM_INDX, 2},
    /* 0xE2 */ ILL,
    /* 0xE3 */ ILL,
    /* 0xE4 */ {MN_CPX, AM_ZP, 2},
    /* 0xE5 */ {MN_SBC, AM_ZP, 2},
    /* 0xE6 */ {MN_INC, AM_ZP, 2},
    /* 0xE7 */ ILL,
    /* 0xE8 */ {MN_INX, AM_IMP, 1},
    /* 0xE9 */ {MN_SBC, AM_IMM, 2},
    /* 0xEA */ {MN_NOP, AM_IMP, 1},
    /* 0xEB */ ILL,
    /* 0xEC */ {MN_CPX, AM_ABS, 3},
    /* 0xED */ {MN_SBC, AM_ABS, 3},
    /* 0xEE */ {MN_INC, AM_ABS, 3},
    /* 0xEF */ ILL,
    /* 0xF0 */ {MN_BEQ, AM_REL, 2},
    /* 0xF1 */ {MN_SBC, AM_INDY, 2},
    /* 0xF2 */ ILL,
    /* 0xF3 */ ILL,
    /* 0xF4 */ ILL,
    /* 0xF5 */ {MN_SBC, AM_ZPX, 2},
    /* 0xF6 */ {MN_INC, AM_ZPX, 2},
    /* 0xF7 */ ILL,
    /* 0xF8 */ {MN_SED, AM_IMP, 1},
    /* 0xF9 */ {MN_SBC, AM_ABSY, 3},
    /* 0xFA */ ILL,
    /* 0xFB */ ILL,
    /* 0xFC */ ILL,
    /* 0xFD */ {MN_SBC, AM_ABSX, 3},
    /* 0xFE */ {MN_INC, AM_ABSX, 3},
    /* 0xFF */ ILL,
};

const char *mnemonic_name(OpMnemonic mn) {
    static const char *names[] = {
        "ADC","AND","ASL","BCC","BCS","BEQ","BIT","BMI",
        "BNE","BPL","BRK","BVC","BVS","CLC","CLD","CLI",
        "CLV","CMP","CPX","CPY","DEC","DEX","DEY","EOR",
        "INC","INX","INY","JMP","JSR","LDA","LDX","LDY",
        "LSR","NOP","ORA","PHA","PHP","PLA","PLP","ROL",
        "ROR","RTI","RTS","SBC","SEC","SED","SEI","STA",
        "STX","STY","TAX","TAY","TSX","TXA","TXS","TYA",
        "???"
    };
    if (mn > MN_ILLEGAL) mn = MN_ILLEGAL;
    return names[mn];
}

const char *addrmode_name(AddrMode am) {
    static const char *names[] = {
        "IMP","ACC","IMM","ZP","ZPX","ZPY","REL","ABS","ABSX","ABSY","IND","INDX","INDY"
    };
    return names[am];
}
