"""
build_symbols_from_lbl.py — Convert a ca65/ld65 label file into a nesrecomp
symbols.sym file.

Designed to ingest FCEUX/Nintendulator NL-format labels that ld65 emits via
`-Ln <file>`:

    al 00XXXX .LabelName

And produce nesrecomp's symbol_file format:

    XXXX LabelName [type]

Where `type` is one of {ram, func} classified by the 6502 address range.
nesrecomp's symbol_lookup keys on the 16-bit address only (no bank), so when
multiple banks define labels at the same runtime address, this script keeps
the longest name.

Example usage:

    # Assemble + link with debug/label output
    ca65 -g --debug-info src/main.asm -o main.o
    ld65 --dbgfile main.dbg -Ln main.lbl -C layout main.o -o main.nes

    # Convert to nesrecomp format
    python build_symbols_from_lbl.py main.lbl symbols.sym \\
        --header "My Game (NES)" \\
        --source "github.com/author/my-game-disassembly"

Then wire into your game.toml:

    [game]
    output_prefix = "my-game"
    symbol_file = "symbols.sym"
"""
from __future__ import annotations
import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

# FCEUX NL label line: `al 00XXXX .LabelName`
LBL_RE = re.compile(r"^al\s+00([0-9A-Fa-f]{4})\s+\.(\S+)")


def classify(addr: int) -> str:
    """Return the nesrecomp symbol-type tag for an address.

    <$2000  → ram (CPU RAM, zero page + stack + main RAM mirrors)
    <$8000  → ram (PPU/APU/IO registers, cartridge RAM — not typical code)
    >=$8000 → func (PRG ROM — code region)
    """
    if addr < 0x8000:
        return "ram"
    return "func"


def parse_lbl(path: Path, drop_locals: bool = True,
              min_len: int = 3) -> dict[int, list[str]]:
    """Parse an NL-format .lbl file into {addr: [name, ...]}.

    drop_locals: skip ca65 cheap-local labels (@-prefixed) — these are
        scoped to a single function and reused, not globally meaningful.
    min_len: skip labels with names <= min_len chars (usually auto-generated
        positional labels like "L1", "C2").
    """
    candidates: dict[int, list[str]] = defaultdict(list)
    with path.open() as f:
        for line in f:
            m = LBL_RE.match(line.strip())
            if not m:
                continue
            addr = int(m.group(1), 16)
            name = m.group(2)
            if drop_locals and name.startswith("@"):
                continue
            if len(name) < min_len:
                continue
            candidates[addr].append(name)
    return candidates


def pick_canonical(names: list[str]) -> str:
    """Pick the canonical name when an address has multiple candidates.

    Current heuristic: longest wins (descriptive names usually > short ones).
    Ties broken by lexical order for deterministic output.
    """
    return max(names, key=lambda n: (len(n), n))


def write_sym(out: Path, entries: dict[int, str],
              header: str | None, source: str | None) -> None:
    with out.open("w", newline="\n") as f:
        if header:
            f.write(f"# {header} Symbol Table\n")
        if source:
            f.write(f"# Source: {source}\n")
        f.write("# Generated by nesrecomp/tools/build_symbols_from_lbl.py\n")
        f.write("# Format: HEXADDR SymbolName [type]\n")
        f.write("#\n")
        f.write("# NOTE: nesrecomp's symbol_lookup keys on uint16_t only\n")
        f.write("# (no bank differentiation). When multiple banks define a\n")
        f.write("# label at the same runtime address, the longest name wins.\n")
        f.write("\n")
        for addr in sorted(entries):
            name = entries[addr]
            f.write(f"{addr:04X} {name} {classify(addr)}\n")


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Convert a ca65/ld65 NL-format .lbl file into a "
                    "nesrecomp symbols.sym file.")
    p.add_argument("lbl", type=Path,
                   help="Input .lbl file from ld65 -Ln")
    p.add_argument("sym", type=Path,
                   help="Output symbols.sym path")
    p.add_argument("--header", type=str, default=None,
                   help="Comment header (e.g. 'Super Mario Bros. (NES)')")
    p.add_argument("--source", type=str, default=None,
                   help="Source attribution (e.g. 'github.com/user/repo')")
    p.add_argument("--keep-locals", action="store_true",
                   help="Keep ca65 @-prefixed cheap locals (default: drop)")
    p.add_argument("--min-name-len", type=int, default=3,
                   help="Minimum label name length (default: 3)")
    p.add_argument("--verbose", "-v", action="store_true",
                   help="Print extraction stats to stderr")
    args = p.parse_args(argv)

    if not args.lbl.exists():
        print(f"error: {args.lbl} not found", file=sys.stderr)
        return 2

    candidates = parse_lbl(args.lbl,
                           drop_locals=not args.keep_locals,
                           min_len=args.min_name_len)
    final = {addr: pick_canonical(names) for addr, names in candidates.items()}
    write_sym(args.sym, final, args.header, args.source)

    if args.verbose:
        total_names = sum(len(v) for v in candidates.values())
        collisions = sum(1 for v in candidates.values() if len(v) > 1)
        print(f"read {total_names} labels from {args.lbl}", file=sys.stderr)
        print(f"wrote {len(final)} unique symbols to {args.sym}",
              file=sys.stderr)
        print(f"address collisions: {collisions}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
