#!/usr/bin/env python3
"""
extract_palettes.py — Extract palette data from ROM and write to assets/palettes.h
For Faxanadu (CHR RAM game), palette is stored in PRG ROM as raw data.
"""
import sys
import os

def extract_palettes(rom_path, out_path):
    with open(rom_path, 'rb') as f:
        data = f.read()

    prg_banks = data[4]
    has_trainer = bool(data[6] & 0x04)
    prg_start = 16 + (512 if has_trainer else 0)
    prg_data = data[prg_start:prg_start + prg_banks * 0x4000]

    # NES system palette (NTSC) for reference
    nes_palette = [
        0x545454, 0x001E74, 0x081090, 0x300088, 0x440064, 0x5C0030, 0x540400, 0x3C1800,
        0x202A00, 0x083A00, 0x004000, 0x003C00, 0x00323C, 0x000000, 0x000000, 0x000000,
        0x989698, 0x084CC4, 0x3032EC, 0x5C1EE4, 0x8814B0, 0xA01464, 0x982220, 0x783C00,
        0x545A00, 0x287200, 0x087C00, 0x007628, 0x006678, 0x000000, 0x000000, 0x000000,
        0xECEEEC, 0x4C9AEC, 0x787CEC, 0xB062EC, 0xE454EC, 0xEC58B4, 0xEC6A64, 0xD48820,
        0xA0AA00, 0x74C400, 0x4CD020, 0x38CC6C, 0x38B4CC, 0x3C3C3C, 0x000000, 0x000000,
        0xECEEEC, 0xA8CCEC, 0xBCBCEC, 0xD4B2EC, 0xECAEEC, 0xECAED4, 0xECB4B0, 0xE4C490,
        0xCCD278, 0xB4DE78, 0xA8E290, 0x98E2B4, 0xA0D6E4, 0xA0A2A0, 0x000000, 0x000000,
    ]

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w') as f:
        f.write("/* AUTO-GENERATED by extract_palettes.py. DO NOT EDIT. */\n")
        f.write("#pragma once\n")
        f.write("/* NES system palette (64 entries, RGB888) */\n")
        f.write("static const unsigned int nes_system_palette[64] = {\n")
        for i, c in enumerate(nes_palette):
            f.write(f"    0x{c:06X}{',' if i < 63 else ''}")
            if (i + 1) % 8 == 0:
                f.write("\n")
        f.write("};\n")

    print(f"Wrote NES system palette → {out_path}")


if __name__ == '__main__':
    rom = sys.argv[1] if len(sys.argv) > 1 else 'F:/Projects/nesrecomp/baserom.nes'
    out = sys.argv[2] if len(sys.argv) > 2 else 'F:/Projects/nesrecomp/assets/palettes.h'
    extract_palettes(rom, out)
