#!/usr/bin/env python3
"""
extract_chr.py — Extract CHR tiles from NES ROM and write to assets/chr_tiles.h
Usage: python extract_chr.py [baserom.nes]
"""
import sys
import os

def extract_chr(rom_path, out_path):
    with open(rom_path, 'rb') as f:
        data = f.read()

    prg_banks = data[4]
    chr_banks = data[5]
    has_trainer = bool(data[6] & 0x04)
    prg_start = 16 + (512 if has_trainer else 0)

    if chr_banks == 0:
        print("No CHR ROM (CHR RAM game). Cannot extract tiles from ROM.")
        print("Tiles are loaded at runtime by the game code.")
        # Create empty header
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        with open(out_path, 'w') as f:
            f.write("/* chr_tiles.h — CHR RAM game: tiles loaded at runtime */\n")
            f.write("#pragma once\n")
            f.write("/* No CHR ROM data for Faxanadu (Mapper 2, CHR RAM) */\n")
        print(f"Wrote empty {out_path}")
        return

    chr_start = prg_start + prg_banks * 0x4000
    chr_size = chr_banks * 0x2000
    chr_data = data[chr_start:chr_start + chr_size]

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w') as f:
        f.write("/* AUTO-GENERATED by extract_chr.py. DO NOT EDIT. */\n")
        f.write("#pragma once\n")
        f.write(f"#define CHR_TILE_COUNT {len(chr_data) // 16}\n")
        f.write(f"static const unsigned char chr_tiles[] = {{\n")
        for i in range(0, len(chr_data), 16):
            chunk = chr_data[i:i+16]
            hex_vals = ', '.join(f'0x{b:02X}' for b in chunk)
            f.write(f"    {hex_vals},\n")
        f.write("};\n")

    print(f"Extracted {len(chr_data)//16} tiles → {out_path}")


if __name__ == '__main__':
    rom = sys.argv[1] if len(sys.argv) > 1 else 'F:/Projects/nesrecomp/baserom.nes'
    out = sys.argv[2] if len(sys.argv) > 2 else 'F:/Projects/nesrecomp/assets/chr_tiles.h'
    extract_chr(rom, out)
