#!/usr/bin/env python3
"""
extract_metasprites.py — Extract metasprite definitions → assets/metasprites.h
Note: Metasprite addresses must be confirmed with Ghidra before use.
"""
import sys
import os

def extract_metasprites(rom_path, out_path):
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w') as f:
        f.write("/* AUTO-GENERATED by extract_metasprites.py. DO NOT EDIT. */\n")
        f.write("#pragma once\n")
        f.write("/* Metasprite data — requires Ghidra verification before use. */\n")
        f.write("/* TODO: Locate metasprite table in Ghidra, then implement. */\n")

    print(f"Wrote stub {out_path} — requires Ghidra analysis to implement")


if __name__ == '__main__':
    rom = sys.argv[1] if len(sys.argv) > 1 else 'F:/Projects/nesrecomp/baserom.nes'
    out = sys.argv[2] if len(sys.argv) > 2 else 'F:/Projects/nesrecomp/assets/metasprites.h'
    extract_metasprites(rom, out)
