#!/usr/bin/env python3
"""
extract_player_sprites.py — Extract player sprite definitions → assets/player_sprites.h
Note: Requires Ghidra analysis to locate sprite data addresses.
"""
import sys
import os

def extract_player_sprites(rom_path, out_path):
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w') as f:
        f.write("/* AUTO-GENERATED by extract_player_sprites.py. DO NOT EDIT. */\n")
        f.write("#pragma once\n")
        f.write("/* Player sprite data — requires Ghidra verification before use. */\n")
        f.write("/* TODO: Locate player sprite table in Ghidra, then implement. */\n")

    print(f"Wrote stub {out_path} — requires Ghidra analysis to implement")


if __name__ == '__main__':
    rom = sys.argv[1] if len(sys.argv) > 1 else 'F:/Projects/nesrecomp/baserom.nes'
    out = sys.argv[2] if len(sys.argv) > 2 else 'F:/Projects/nesrecomp/assets/player_sprites.h'
    extract_player_sprites(rom, out)
