/*
 * cpu6502.h - NESRecomp's cycle-accurate 2A03 CPU core (NMOS 6502, no decimal
 * mode).
 *
 * The CPU is shared by two users:
 *   - code generated by NESRecomp --cycle-accurate (<prefix>_cyc.c), one
 *     labeled block per ROM instruction with operands folded to constants;
 *   - cpu6502_interp.c, the interpreter for everything else (code in RAM,
 *     open bus, addresses the recompiler did not reach), generated from the
 *     same instruction templates by NESRecomp --emit-cycle-interpreter.
 *
 * Both run whole instructions, spelled out one CPU cycle at a time with
 * cpu_read/cpu_write below, and hand over to each other only at instruction
 * boundaries. The rest of the machine is behind hw.h.
 *
 * Cycle order and bus activity follow the NMOS 6502 (addressing-mode cycle
 * tables, dummy reads and writes, interrupt polling in the last cycle, taken
 * branches polling only on a page crossing) including the undocumented
 * opcodes and the 2A03's DMA interactions.
 */
#pragma once
#include <stdbool.h>
#include <stdint.h>

#include "cyc_trace.h"
#include "hw.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    uint16_t pc;
    uint8_t  a, x, y, s;
    uint8_t  c, z, i, d, v, n;   /* status flags, each 0 or 1 */
    /* Interrupt inputs. The NMI edge detector samples the line once per
     * cycle (cpu_nmi_input) and latches a rising edge until the NMI vector
     * is taken; do_* are what the opcode fetch checks, set by the polls. */
    uint8_t  nmi_input, nmi_edge;
    uint8_t  do_nmi, do_irq, do_reset;
    /* Set by a jam (HLT) opcode: the CPU only reads $FFFF from then on. */
    uint8_t  jammed;
    /* The power-on reset sequence has not run yet. */
    uint8_t  power_on;
} Cpu6502;

extern Cpu6502 cpu;

/* Flags for one CPU cycle. */
enum {
    CYC_POLL        = 1,  /* sample the interrupt lines before the access */
    CYC_POLL_BRANCH = 2,  /* a taken branch's page-crossing cycle: like
                             CYC_POLL, but an IRQ latched by the branch's
                             first poll stays latched */
    CYC_DONE        = 4,  /* this cycle completes the instruction */
};

/* P as pushed: bit 5 always set, B (bit 4) as given. */
static inline uint8_t cpu_get_p(uint8_t b_flag) {
    return (uint8_t)(cpu.n << 7 | cpu.v << 6 | 0x20 | b_flag << 4 | cpu.d << 3 | cpu.i << 2 | cpu.z << 1 | cpu.c);
}
static inline void cpu_set_p(uint8_t p) {
    cpu.c = p & 1; cpu.z = (p >> 1) & 1; cpu.i = (p >> 2) & 1;
    cpu.d = (p >> 3) & 1; cpu.v = (p >> 6) & 1; cpu.n = p >> 7;
}

static inline void cpu_poll(unsigned f) {
    if (cpu.nmi_edge) cpu.do_nmi = 1;
    if ((f & CYC_POLL) || !cpu.do_irq) cpu.do_irq = hw_irq_line() && !cpu.i;
}

static inline uint8_t cpu_read(uint16_t addr, unsigned f) {
    hw_cycle_start(addr, HW_READ);
    if (f & (CYC_POLL | CYC_POLL_BRANCH)) cpu_poll(f);
    uint8_t value = hw_read(addr);
    hw_cycle_finish((f & CYC_DONE) != 0);
    return value;
}

/* cpu_read() of a PRG ROM byte the recompiler folded to a constant. */
static inline uint8_t cpu_read_rom(uint16_t addr, uint8_t value, unsigned f) {
    hw_cycle_start(addr, HW_READ);
    if (f & (CYC_POLL | CYC_POLL_BRANCH)) cpu_poll(f);
    hw_read_rom(addr, value);
    hw_cycle_finish((f & CYC_DONE) != 0);
    return value;
}

static inline void cpu_write(uint16_t addr, uint8_t value, unsigned f) {
    hw_cycle_start(addr, HW_WRITE);
    if (f & CYC_POLL) cpu_poll(f);
    hw_write(addr, value);
    hw_cycle_finish((f & CYC_DONE) != 0);
}

static inline void cpu_trace_instruction(uint16_t pc) {
    cyc_trace_instruction(pc, cpu.a, cpu.x, cpu.y, cpu.s, (uint8_t)(cpu_get_p(0) & 0xCF));
}

/* The opcode fetch cycle of the instruction at pc. Returns true if an NMI,
 * IRQ or reset is pending: the opcode is then discarded, and the caller runs
 * cpu_interrupt() with cpu.pc still at this instruction. The trace records
 * the instruction after any DMA cycles that delay the fetch. */
static inline bool cpu_fetch_rom(uint16_t pc, uint8_t opcode) {
    hw_cycle_start(pc, HW_READ);
    if (cyc_trace_enabled) cpu_trace_instruction(pc);
    hw_read_rom(pc, opcode);
    hw_cycle_finish(false);
    return (cpu.do_nmi | cpu.do_irq | cpu.do_reset) != 0;
}

static inline bool cpu_fetch(uint16_t pc, uint8_t *opcode) {
    hw_cycle_start(pc, HW_READ);
    if (cyc_trace_enabled) cpu_trace_instruction(pc);
    *opcode = hw_read(pc);
    hw_cycle_finish(false);
    return (cpu.do_nmi | cpu.do_irq | cpu.do_reset) != 0;
}

/* ---- status register and operations shared by the templates ---- */

static inline void cpu_nz(uint8_t value) {
    cpu.z = value == 0;
    cpu.n = value >> 7;
}
static inline void cpu_adc(uint8_t value) {
    unsigned sum = (unsigned)cpu.a + value + cpu.c;
    cpu.v = ((~(cpu.a ^ value) & (cpu.a ^ sum)) >> 7) & 1;
    cpu.c = sum > 0xFF;
    cpu.a = (uint8_t)sum;
    cpu_nz(cpu.a);
}
static inline void cpu_sbc(uint8_t value) {
    int diff = (int)cpu.a - value - (cpu.c ? 0 : 1);
    cpu.v = (((cpu.a ^ value) & (cpu.a ^ diff)) >> 7) & 1;
    cpu.c = diff >= 0;
    cpu.a = (uint8_t)diff;
    cpu_nz(cpu.a);
}
static inline void cpu_cmp(uint8_t reg, uint8_t value) {
    cpu.c = reg >= value;
    cpu_nz((uint8_t)(reg - value));
}
static inline void cpu_bit(uint8_t value) {
    cpu.z = (cpu.a & value) == 0;
    cpu.v = (value >> 6) & 1;
    cpu.n = value >> 7;
}
static inline uint8_t cpu_asl(uint8_t value) {
    cpu.c = value >> 7;
    value = (uint8_t)(value << 1);
    cpu_nz(value);
    return value;
}
static inline uint8_t cpu_lsr(uint8_t value) {
    cpu.c = value & 1;
    value >>= 1;
    cpu_nz(value);
    return value;
}
static inline uint8_t cpu_rol(uint8_t value) {
    uint8_t result = (uint8_t)(value << 1 | cpu.c);
    cpu.c = value >> 7;
    cpu_nz(result);
    return result;
}
static inline uint8_t cpu_ror(uint8_t value) {
    uint8_t result = (uint8_t)(value >> 1 | cpu.c << 7);
    cpu.c = value & 1;
    cpu_nz(result);
    return result;
}

/* ---- sequences that are not instruction templates (cpu6502.c) ---- */

/* Power-on state: registers cleared, reset pending. */
void cpu_power_on(void);
/* The power-on cycle and reset sequence; runs when cpu.power_on is set. */
void cpu_power_on_sequence(void);
/* The six cycles after an interrupted opcode fetch (brk = false), or after a
 * BRK opcode's fetch (brk = true, cpu.pc at the BRK). Leaves cpu.pc at the
 * handler. An NMI polled during the sequence takes over its vector. */
void cpu_interrupt(bool brk);
/* The cycles after a jam opcode's fetch (cpu.pc at the opcode). */
void cpu_jam(void);
/* One cycle of a jammed CPU. */
void cpu_jam_cycle(void);

/* Execute one instruction at cpu.pc on the interpreter (cpu6502_interp.c).
 * Includes interrupt entry when one is pending. */
void cpu_interp_step(void);

#ifdef __cplusplus
}
#endif
