/* cpu6502_interp.c - generated by NESRecomp --emit-cycle-interpreter. DO NOT EDIT.
 *
 * The cycle-accurate 6502 interpreter: the instruction templates of
 * recompiler/src/cyc_codegen.c with operands read at run time. Recompiled
 * code (<prefix>_cyc.c) is generated from the same templates. Regenerate with
 *   NESRecomp --emit-cycle-interpreter runner/cyc/cpu6502_interp.c */
#include "cpu6502.h"

void cpu_interp_step(void) {
    uint16_t pc = cpu.pc;
    uint8_t opcode, b1 = 0, b2 = 0;
    if (cpu_fetch(pc, &opcode)) { cpu_interrupt(false); return; }
    switch (opcode) {
    case 0x00: { /* BRK */
        cpu_interrupt(true);
        return;
    }
    case 0x01: { /* ORA (zp,X) */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint8_t lo = cpu_read((uint8_t)(b1 + cpu.x), 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + cpu.x + 1), 0);
        uint16_t ea = (uint16_t)(lo | hi << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a |= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x02: { /* HLT */
        cpu_jam();
        return;
    }
    case 0x03: { /* SLO (zp,X) */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint8_t lo = cpu_read((uint8_t)(b1 + cpu.x), 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + cpu.x + 1), 0);
        uint16_t ea = (uint16_t)(lo | hi << 8);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_asl(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a |= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x04: { /* NOP zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x05: { /* ORA zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a |= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x06: { /* ASL zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_asl(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x07: { /* SLO zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_asl(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a |= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x08: { /* PHP */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_write((uint16_t)(0x100 | cpu.s), cpu_get_p(1), CYC_POLL | CYC_DONE);
        cpu.s--;
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x09: { /* ORA # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.a |= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x0A: { /* ASL */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.a = cpu_asl(cpu.a);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x0B: { /* ANC # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.a &= v; cpu_nz(cpu.a); cpu.c = cpu.n;
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x0C: { /* NOP abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x0D: { /* ORA abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a |= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x0E: { /* ASL abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_asl(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x0F: { /* SLO abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_asl(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a |= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x10: { /* BPL */
        if (cpu.n) { cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE); cpu.pc = (uint16_t)(pc + 2); return; }
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL);
        uint16_t next = (uint16_t)(pc + 2), target = (uint16_t)(next + (int8_t)b1);
        if (((target ^ next) & 0xFF00) == 0) {
            cpu_read(next, CYC_DONE);
        } else {
            cpu_read(next, 0);
            cpu_read((uint16_t)((next & 0xFF00) | (target & 0xFF)), CYC_POLL_BRANCH | CYC_DONE);
        }
        cpu.pc = target;
        return;
    }
    case 0x11: { /* ORA (zp),Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint8_t lo = cpu_read(b1, 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + 1), 0);
        uint16_t base = (uint16_t)(lo | hi << 8), ea = (uint16_t)(base + cpu.y);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a |= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x12: { /* HLT */
        cpu_jam();
        return;
    }
    case 0x13: { /* SLO (zp),Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint8_t lo = cpu_read(b1, 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + 1), 0);
        uint16_t base = (uint16_t)(lo | hi << 8), ea = (uint16_t)(base + cpu.y);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_asl(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a |= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x14: { /* NOP zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x15: { /* ORA zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a |= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x16: { /* ASL zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_asl(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x17: { /* SLO zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_asl(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a |= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x18: { /* CLC */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.c = 0;
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x19: { /* ORA abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a |= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x1A: { /* NOP */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x1B: { /* SLO abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_asl(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a |= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x1C: { /* NOP abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x1D: { /* ORA abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a |= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x1E: { /* ASL abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_asl(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x1F: { /* SLO abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_asl(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a |= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x20: { /* JSR abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read((uint16_t)(0x100 | cpu.s), 0);
        cpu_write((uint16_t)(0x100 | cpu.s), (uint8_t)((pc + 2) >> 8), 0);
        cpu_write((uint16_t)(0x100 | (uint8_t)(cpu.s - 1)), (uint8_t)(pc + 2), 0);
        b2 = cpu_read((uint16_t)(pc + 2), CYC_POLL | CYC_DONE);
        cpu.s = (uint8_t)(cpu.s - 2);
        cpu.pc = (uint16_t)(b1 | b2 << 8);
        return;
    }
    case 0x21: { /* AND (zp,X) */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint8_t lo = cpu_read((uint8_t)(b1 + cpu.x), 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + cpu.x + 1), 0);
        uint16_t ea = (uint16_t)(lo | hi << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a &= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x22: { /* HLT */
        cpu_jam();
        return;
    }
    case 0x23: { /* RLA (zp,X) */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint8_t lo = cpu_read((uint8_t)(b1 + cpu.x), 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + cpu.x + 1), 0);
        uint16_t ea = (uint16_t)(lo | hi << 8);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_rol(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a &= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x24: { /* BIT zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_bit(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x25: { /* AND zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a &= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x26: { /* ROL zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_rol(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x27: { /* RLA zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_rol(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a &= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x28: { /* PLP */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read((uint16_t)(0x100 | cpu.s), 0);
        cpu.s++;
        cpu_set_p(cpu_read((uint16_t)(0x100 | cpu.s), CYC_POLL | CYC_DONE));
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x29: { /* AND # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.a &= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x2A: { /* ROL */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.a = cpu_rol(cpu.a);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x2B: { /* ANC # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.a &= v; cpu_nz(cpu.a); cpu.c = cpu.n;
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x2C: { /* BIT abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_bit(v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x2D: { /* AND abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a &= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x2E: { /* ROL abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_rol(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x2F: { /* RLA abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_rol(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a &= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x30: { /* BMI */
        if (!cpu.n) { cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE); cpu.pc = (uint16_t)(pc + 2); return; }
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL);
        uint16_t next = (uint16_t)(pc + 2), target = (uint16_t)(next + (int8_t)b1);
        if (((target ^ next) & 0xFF00) == 0) {
            cpu_read(next, CYC_DONE);
        } else {
            cpu_read(next, 0);
            cpu_read((uint16_t)((next & 0xFF00) | (target & 0xFF)), CYC_POLL_BRANCH | CYC_DONE);
        }
        cpu.pc = target;
        return;
    }
    case 0x31: { /* AND (zp),Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint8_t lo = cpu_read(b1, 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + 1), 0);
        uint16_t base = (uint16_t)(lo | hi << 8), ea = (uint16_t)(base + cpu.y);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a &= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x32: { /* HLT */
        cpu_jam();
        return;
    }
    case 0x33: { /* RLA (zp),Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint8_t lo = cpu_read(b1, 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + 1), 0);
        uint16_t base = (uint16_t)(lo | hi << 8), ea = (uint16_t)(base + cpu.y);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_rol(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a &= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x34: { /* NOP zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x35: { /* AND zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a &= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x36: { /* ROL zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_rol(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x37: { /* RLA zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_rol(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a &= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x38: { /* SEC */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.c = 1;
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x39: { /* AND abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a &= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x3A: { /* NOP */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x3B: { /* RLA abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_rol(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a &= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x3C: { /* NOP abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x3D: { /* AND abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a &= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x3E: { /* ROL abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_rol(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x3F: { /* RLA abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_rol(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a &= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x40: { /* RTI */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read((uint16_t)(0x100 | cpu.s), 0);
        cpu_set_p(cpu_read((uint16_t)(0x100 | (uint8_t)(cpu.s + 1)), 0));
        uint8_t lo = cpu_read((uint16_t)(0x100 | (uint8_t)(cpu.s + 2)), 0);
        uint8_t hi = cpu_read((uint16_t)(0x100 | (uint8_t)(cpu.s + 3)), CYC_POLL | CYC_DONE);
        cpu.s = (uint8_t)(cpu.s + 3);
        cpu.pc = (uint16_t)(lo | hi << 8);
        return;
    }
    case 0x41: { /* EOR (zp,X) */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint8_t lo = cpu_read((uint8_t)(b1 + cpu.x), 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + cpu.x + 1), 0);
        uint16_t ea = (uint16_t)(lo | hi << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a ^= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x42: { /* HLT */
        cpu_jam();
        return;
    }
    case 0x43: { /* SRE (zp,X) */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint8_t lo = cpu_read((uint8_t)(b1 + cpu.x), 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + cpu.x + 1), 0);
        uint16_t ea = (uint16_t)(lo | hi << 8);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_lsr(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a ^= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x44: { /* NOP zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x45: { /* EOR zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a ^= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x46: { /* LSR zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_lsr(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x47: { /* SRE zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_lsr(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a ^= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x48: { /* PHA */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_write((uint16_t)(0x100 | cpu.s), cpu.a, CYC_POLL | CYC_DONE);
        cpu.s--;
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x49: { /* EOR # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.a ^= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x4A: { /* LSR */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.a = cpu_lsr(cpu.a);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x4B: { /* ASR # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.a = cpu_lsr((uint8_t)(cpu.a & v));
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x4C: { /* JMP abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(b1 | b2 << 8);
        return;
    }
    case 0x4D: { /* EOR abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a ^= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x4E: { /* LSR abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_lsr(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x4F: { /* SRE abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_lsr(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a ^= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x50: { /* BVC */
        if (cpu.v) { cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE); cpu.pc = (uint16_t)(pc + 2); return; }
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL);
        uint16_t next = (uint16_t)(pc + 2), target = (uint16_t)(next + (int8_t)b1);
        if (((target ^ next) & 0xFF00) == 0) {
            cpu_read(next, CYC_DONE);
        } else {
            cpu_read(next, 0);
            cpu_read((uint16_t)((next & 0xFF00) | (target & 0xFF)), CYC_POLL_BRANCH | CYC_DONE);
        }
        cpu.pc = target;
        return;
    }
    case 0x51: { /* EOR (zp),Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint8_t lo = cpu_read(b1, 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + 1), 0);
        uint16_t base = (uint16_t)(lo | hi << 8), ea = (uint16_t)(base + cpu.y);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a ^= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x52: { /* HLT */
        cpu_jam();
        return;
    }
    case 0x53: { /* SRE (zp),Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint8_t lo = cpu_read(b1, 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + 1), 0);
        uint16_t base = (uint16_t)(lo | hi << 8), ea = (uint16_t)(base + cpu.y);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_lsr(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a ^= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x54: { /* NOP zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x55: { /* EOR zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a ^= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x56: { /* LSR zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_lsr(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x57: { /* SRE zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_lsr(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a ^= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x58: { /* CLI */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.i = 0;
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x59: { /* EOR abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a ^= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x5A: { /* NOP */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x5B: { /* SRE abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_lsr(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a ^= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x5C: { /* NOP abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x5D: { /* EOR abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a ^= v; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x5E: { /* LSR abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_lsr(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x5F: { /* SRE abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_lsr(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.a ^= r; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x60: { /* RTS */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read((uint16_t)(0x100 | cpu.s), 0);
        uint8_t lo = cpu_read((uint16_t)(0x100 | (uint8_t)(cpu.s + 1)), 0);
        uint8_t hi = cpu_read((uint16_t)(0x100 | (uint8_t)(cpu.s + 2)), 0);
        cpu_read((uint16_t)(lo | hi << 8), CYC_POLL | CYC_DONE);
        cpu.s = (uint8_t)(cpu.s + 2);
        cpu.pc = (uint16_t)((lo | hi << 8) + 1);
        return;
    }
    case 0x61: { /* ADC (zp,X) */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint8_t lo = cpu_read((uint8_t)(b1 + cpu.x), 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + cpu.x + 1), 0);
        uint16_t ea = (uint16_t)(lo | hi << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_adc(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x62: { /* HLT */
        cpu_jam();
        return;
    }
    case 0x63: { /* RRA (zp,X) */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint8_t lo = cpu_read((uint8_t)(b1 + cpu.x), 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + cpu.x + 1), 0);
        uint16_t ea = (uint16_t)(lo | hi << 8);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_ror(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_adc(r);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x64: { /* NOP zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x65: { /* ADC zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_adc(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x66: { /* ROR zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_ror(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x67: { /* RRA zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_ror(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_adc(r);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x68: { /* PLA */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read((uint16_t)(0x100 | cpu.s), 0);
        cpu.s++;
        cpu.a = cpu_read((uint16_t)(0x100 | cpu.s), CYC_POLL | CYC_DONE);
        cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x69: { /* ADC # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu_adc(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x6A: { /* ROR */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.a = cpu_ror(cpu.a);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x6B: { /* ARR # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.a = cpu_ror((uint8_t)(cpu.a & v)); cpu.c = (cpu.a >> 6) & 1; cpu.v = ((cpu.a >> 5) ^ (cpu.a >> 6)) & 1;
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x6C: { /* JMP (abs) */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ptr = (uint16_t)(b1 | b2 << 8);
        uint8_t lo = cpu_read(ptr, 0);
        uint8_t hi = cpu_read((uint16_t)((ptr & 0xFF00) | ((ptr + 1) & 0xFF)), CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(lo | hi << 8);
        return;
    }
    case 0x6D: { /* ADC abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_adc(v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x6E: { /* ROR abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_ror(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x6F: { /* RRA abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_ror(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_adc(r);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x70: { /* BVS */
        if (!cpu.v) { cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE); cpu.pc = (uint16_t)(pc + 2); return; }
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL);
        uint16_t next = (uint16_t)(pc + 2), target = (uint16_t)(next + (int8_t)b1);
        if (((target ^ next) & 0xFF00) == 0) {
            cpu_read(next, CYC_DONE);
        } else {
            cpu_read(next, 0);
            cpu_read((uint16_t)((next & 0xFF00) | (target & 0xFF)), CYC_POLL_BRANCH | CYC_DONE);
        }
        cpu.pc = target;
        return;
    }
    case 0x71: { /* ADC (zp),Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint8_t lo = cpu_read(b1, 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + 1), 0);
        uint16_t base = (uint16_t)(lo | hi << 8), ea = (uint16_t)(base + cpu.y);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_adc(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x72: { /* HLT */
        cpu_jam();
        return;
    }
    case 0x73: { /* RRA (zp),Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint8_t lo = cpu_read(b1, 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + 1), 0);
        uint16_t base = (uint16_t)(lo | hi << 8), ea = (uint16_t)(base + cpu.y);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_ror(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_adc(r);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x74: { /* NOP zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x75: { /* ADC zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_adc(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x76: { /* ROR zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_ror(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x77: { /* RRA zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_ror(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_adc(r);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x78: { /* SEI */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.i = 1;
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x79: { /* ADC abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_adc(v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x7A: { /* NOP */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x7B: { /* RRA abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_ror(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_adc(r);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x7C: { /* NOP abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x7D: { /* ADC abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_adc(v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x7E: { /* ROR abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_ror(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x7F: { /* RRA abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = cpu_ror(v);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_adc(r);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x80: { /* NOP # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x81: { /* STA (zp,X) */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint8_t lo = cpu_read((uint8_t)(b1 + cpu.x), 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + cpu.x + 1), 0);
        uint16_t ea = (uint16_t)(lo | hi << 8);
        cpu_write(ea, cpu.a, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x82: { /* NOP # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x83: { /* SAX (zp,X) */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint8_t lo = cpu_read((uint8_t)(b1 + cpu.x), 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + cpu.x + 1), 0);
        uint16_t ea = (uint16_t)(lo | hi << 8);
        cpu_write(ea, (uint8_t)(cpu.a & cpu.x), CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x84: { /* STY zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        cpu_write(ea, cpu.y, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x85: { /* STA zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        cpu_write(ea, cpu.a, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x86: { /* STX zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        cpu_write(ea, cpu.x, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x87: { /* SAX zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        cpu_write(ea, (uint8_t)(cpu.a & cpu.x), CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x88: { /* DEY */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.y--; cpu_nz(cpu.y);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x89: { /* NOP # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x8A: { /* TXA */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.a = cpu.x; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x8B: { /* ANE # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.a = (uint8_t)(cpu.x & v); cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x8C: { /* STY abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        cpu_write(ea, cpu.y, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x8D: { /* STA abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        cpu_write(ea, cpu.a, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x8E: { /* STX abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        cpu_write(ea, cpu.x, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x8F: { /* SAX abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        cpu_write(ea, (uint8_t)(cpu.a & cpu.x), CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x90: { /* BCC */
        if (cpu.c) { cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE); cpu.pc = (uint16_t)(pc + 2); return; }
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL);
        uint16_t next = (uint16_t)(pc + 2), target = (uint16_t)(next + (int8_t)b1);
        if (((target ^ next) & 0xFF00) == 0) {
            cpu_read(next, CYC_DONE);
        } else {
            cpu_read(next, 0);
            cpu_read((uint16_t)((next & 0xFF00) | (target & 0xFF)), CYC_POLL_BRANCH | CYC_DONE);
        }
        cpu.pc = target;
        return;
    }
    case 0x91: { /* STA (zp),Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint8_t lo = cpu_read(b1, 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + 1), 0);
        uint16_t base = (uint16_t)(lo | hi << 8), ea = (uint16_t)(base + cpu.y);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        cpu_write(ea, cpu.a, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x92: { /* HLT */
        cpu_jam();
        return;
    }
    case 0x93: { /* SHA (zp),Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint8_t lo = cpu_read(b1, 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + 1), 0);
        uint16_t base = (uint16_t)(lo | hi << 8), ea = (uint16_t)(base + cpu.y);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        bool ignore_h = hw_dma_stalls != 0;
        uint8_t h = ignore_h ? 0xFF : (uint8_t)((base >> 8) + 1);
        if ((ea ^ base) & 0xFF00) ea = (uint16_t)((ea & 0xFF) | ((ea >> 8) & cpu.x) << 8);
        cpu_write(ea, (uint8_t)(cpu.a & (cpu.x | 0xF5) & h), CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x94: { /* STY zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        cpu_write(ea, cpu.y, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x95: { /* STA zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        cpu_write(ea, cpu.a, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x96: { /* STX zp,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.y);
        cpu_write(ea, cpu.x, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x97: { /* SAX zp,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.y);
        cpu_write(ea, (uint8_t)(cpu.a & cpu.x), CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0x98: { /* TYA */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.a = cpu.y; cpu_nz(cpu.a);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x99: { /* STA abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        cpu_write(ea, cpu.a, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x9A: { /* TXS */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.s = cpu.x;
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0x9B: { /* SHS abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        bool ignore_h = hw_dma_stalls != 0;
        uint8_t h = ignore_h ? 0xFF : (uint8_t)((base >> 8) + 1);
        if ((ea ^ base) & 0xFF00) ea = (uint16_t)((ea & 0xFF) | ((ea >> 8) & cpu.x) << 8);
        cpu.s = (uint8_t)(cpu.a & cpu.x);
        cpu_write(ea, (uint8_t)(cpu.a & (cpu.x | 0xF5) & h), CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x9C: { /* SHY abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        bool ignore_h = hw_dma_stalls != 0;
        uint8_t h = ignore_h ? 0xFF : (uint8_t)((base >> 8) + 1);
        if ((ea ^ base) & 0xFF00) ea = (uint16_t)((ea & 0xFF) | ((ea >> 8) & cpu.y) << 8);
        cpu_write(ea, (uint8_t)(cpu.y & h), CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x9D: { /* STA abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        cpu_write(ea, cpu.a, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x9E: { /* SHX abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        bool ignore_h = hw_dma_stalls != 0;
        uint8_t h = ignore_h ? 0xFF : (uint8_t)((base >> 8) + 1);
        if ((ea ^ base) & 0xFF00) ea = (uint16_t)((ea & 0xFF) | ((ea >> 8) & cpu.x) << 8);
        cpu_write(ea, (uint8_t)(cpu.x & h), CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0x9F: { /* SHA abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        bool ignore_h = hw_dma_stalls != 0;
        uint8_t h = ignore_h ? 0xFF : (uint8_t)((base >> 8) + 1);
        if ((ea ^ base) & 0xFF00) ea = (uint16_t)((ea & 0xFF) | ((ea >> 8) & cpu.x) << 8);
        cpu_write(ea, (uint8_t)(cpu.a & (cpu.x | 0xF5) & h), CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xA0: { /* LDY # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.y = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xA1: { /* LDA (zp,X) */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint8_t lo = cpu_read((uint8_t)(b1 + cpu.x), 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + cpu.x + 1), 0);
        uint16_t ea = (uint16_t)(lo | hi << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xA2: { /* LDX # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.x = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xA3: { /* LAX (zp,X) */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint8_t lo = cpu_read((uint8_t)(b1 + cpu.x), 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + cpu.x + 1), 0);
        uint16_t ea = (uint16_t)(lo | hi << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a = cpu.x = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xA4: { /* LDY zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.y = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xA5: { /* LDA zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xA6: { /* LDX zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.x = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xA7: { /* LAX zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a = cpu.x = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xA8: { /* TAY */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.y = cpu.a; cpu_nz(cpu.y);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0xA9: { /* LDA # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.a = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xAA: { /* TAX */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.x = cpu.a; cpu_nz(cpu.x);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0xAB: { /* LXA # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.a = cpu.x = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xAC: { /* LDY abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.y = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xAD: { /* LDA abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xAE: { /* LDX abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.x = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xAF: { /* LAX abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a = cpu.x = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xB0: { /* BCS */
        if (!cpu.c) { cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE); cpu.pc = (uint16_t)(pc + 2); return; }
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL);
        uint16_t next = (uint16_t)(pc + 2), target = (uint16_t)(next + (int8_t)b1);
        if (((target ^ next) & 0xFF00) == 0) {
            cpu_read(next, CYC_DONE);
        } else {
            cpu_read(next, 0);
            cpu_read((uint16_t)((next & 0xFF00) | (target & 0xFF)), CYC_POLL_BRANCH | CYC_DONE);
        }
        cpu.pc = target;
        return;
    }
    case 0xB1: { /* LDA (zp),Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint8_t lo = cpu_read(b1, 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + 1), 0);
        uint16_t base = (uint16_t)(lo | hi << 8), ea = (uint16_t)(base + cpu.y);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xB2: { /* HLT */
        cpu_jam();
        return;
    }
    case 0xB3: { /* LAX (zp),Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint8_t lo = cpu_read(b1, 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + 1), 0);
        uint16_t base = (uint16_t)(lo | hi << 8), ea = (uint16_t)(base + cpu.y);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a = cpu.x = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xB4: { /* LDY zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.y = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xB5: { /* LDA zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xB6: { /* LDX zp,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.y);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.x = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xB7: { /* LAX zp,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.y);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a = cpu.x = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xB8: { /* CLV */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.v = 0;
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0xB9: { /* LDA abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xBA: { /* TSX */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.x = cpu.s; cpu_nz(cpu.x);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0xBB: { /* LAS abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a = cpu.x = cpu.s = (uint8_t)(v & cpu.s); cpu_nz(cpu.x);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xBC: { /* LDY abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.y = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xBD: { /* LDA abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xBE: { /* LDX abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.x = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xBF: { /* LAX abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu.a = cpu.x = v; cpu_nz(v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xC0: { /* CPY # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.y, v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xC1: { /* CMP (zp,X) */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint8_t lo = cpu_read((uint8_t)(b1 + cpu.x), 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + cpu.x + 1), 0);
        uint16_t ea = (uint16_t)(lo | hi << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.a, v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xC2: { /* NOP # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xC3: { /* DCP (zp,X) */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint8_t lo = cpu_read((uint8_t)(b1 + cpu.x), 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + cpu.x + 1), 0);
        uint16_t ea = (uint16_t)(lo | hi << 8);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v - 1);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.a, r);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xC4: { /* CPY zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.y, v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xC5: { /* CMP zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.a, v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xC6: { /* DEC zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v - 1); cpu_nz(r);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xC7: { /* DCP zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v - 1);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.a, r);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xC8: { /* INY */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.y++; cpu_nz(cpu.y);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0xC9: { /* CMP # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.a, v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xCA: { /* DEX */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.x--; cpu_nz(cpu.x);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0xCB: { /* AXS # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.c = (uint8_t)(cpu.a & cpu.x) >= v; cpu.x = (uint8_t)((cpu.a & cpu.x) - v); cpu_nz(cpu.x);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xCC: { /* CPY abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.y, v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xCD: { /* CMP abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.a, v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xCE: { /* DEC abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v - 1); cpu_nz(r);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xCF: { /* DCP abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v - 1);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.a, r);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xD0: { /* BNE */
        if (cpu.z) { cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE); cpu.pc = (uint16_t)(pc + 2); return; }
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL);
        uint16_t next = (uint16_t)(pc + 2), target = (uint16_t)(next + (int8_t)b1);
        if (((target ^ next) & 0xFF00) == 0) {
            cpu_read(next, CYC_DONE);
        } else {
            cpu_read(next, 0);
            cpu_read((uint16_t)((next & 0xFF00) | (target & 0xFF)), CYC_POLL_BRANCH | CYC_DONE);
        }
        cpu.pc = target;
        return;
    }
    case 0xD1: { /* CMP (zp),Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint8_t lo = cpu_read(b1, 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + 1), 0);
        uint16_t base = (uint16_t)(lo | hi << 8), ea = (uint16_t)(base + cpu.y);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.a, v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xD2: { /* HLT */
        cpu_jam();
        return;
    }
    case 0xD3: { /* DCP (zp),Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint8_t lo = cpu_read(b1, 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + 1), 0);
        uint16_t base = (uint16_t)(lo | hi << 8), ea = (uint16_t)(base + cpu.y);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v - 1);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.a, r);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xD4: { /* NOP zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xD5: { /* CMP zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.a, v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xD6: { /* DEC zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v - 1); cpu_nz(r);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xD7: { /* DCP zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v - 1);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.a, r);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xD8: { /* CLD */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.d = 0;
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0xD9: { /* CMP abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.a, v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xDA: { /* NOP */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0xDB: { /* DCP abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v - 1);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.a, r);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xDC: { /* NOP abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xDD: { /* CMP abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.a, v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xDE: { /* DEC abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v - 1); cpu_nz(r);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xDF: { /* DCP abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v - 1);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.a, r);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xE0: { /* CPX # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.x, v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xE1: { /* SBC (zp,X) */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint8_t lo = cpu_read((uint8_t)(b1 + cpu.x), 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + cpu.x + 1), 0);
        uint16_t ea = (uint16_t)(lo | hi << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_sbc(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xE2: { /* NOP # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xE3: { /* ISC (zp,X) */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint8_t lo = cpu_read((uint8_t)(b1 + cpu.x), 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + cpu.x + 1), 0);
        uint16_t ea = (uint16_t)(lo | hi << 8);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v + 1);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_sbc(r);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xE4: { /* CPX zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.x, v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xE5: { /* SBC zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_sbc(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xE6: { /* INC zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v + 1); cpu_nz(r);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xE7: { /* ISC zp */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint16_t ea = b1;
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v + 1);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_sbc(r);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xE8: { /* INX */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.x++; cpu_nz(cpu.x);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0xE9: { /* SBC # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu_sbc(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xEA: { /* NOP */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0xEB: { /* SBC # */
        uint8_t v = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu_sbc(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xEC: { /* CPX abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_cmp(cpu.x, v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xED: { /* SBC abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_sbc(v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xEE: { /* INC abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v + 1); cpu_nz(r);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xEF: { /* ISC abs */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t ea = (uint16_t)(b1 | b2 << 8);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v + 1);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_sbc(r);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xF0: { /* BEQ */
        if (!cpu.z) { cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE); cpu.pc = (uint16_t)(pc + 2); return; }
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL);
        uint16_t next = (uint16_t)(pc + 2), target = (uint16_t)(next + (int8_t)b1);
        if (((target ^ next) & 0xFF00) == 0) {
            cpu_read(next, CYC_DONE);
        } else {
            cpu_read(next, 0);
            cpu_read((uint16_t)((next & 0xFF00) | (target & 0xFF)), CYC_POLL_BRANCH | CYC_DONE);
        }
        cpu.pc = target;
        return;
    }
    case 0xF1: { /* SBC (zp),Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint8_t lo = cpu_read(b1, 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + 1), 0);
        uint16_t base = (uint16_t)(lo | hi << 8), ea = (uint16_t)(base + cpu.y);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_sbc(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xF2: { /* HLT */
        cpu_jam();
        return;
    }
    case 0xF3: { /* ISC (zp),Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        uint8_t lo = cpu_read(b1, 0);
        uint8_t hi = cpu_read((uint8_t)(b1 + 1), 0);
        uint16_t base = (uint16_t)(lo | hi << 8), ea = (uint16_t)(base + cpu.y);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v + 1);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_sbc(r);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xF4: { /* NOP zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xF5: { /* SBC zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_sbc(v);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xF6: { /* INC zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v + 1); cpu_nz(r);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xF7: { /* ISC zp,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        cpu_read(b1, 0);
        uint16_t ea = (uint8_t)(b1 + cpu.x);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v + 1);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_sbc(r);
        cpu.pc = (uint16_t)(pc + 2);
        return;
    }
    case 0xF8: { /* SED */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.d = 1;
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0xF9: { /* SBC abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_sbc(v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xFA: { /* NOP */
        b1 = cpu_read((uint16_t)(pc + 1), CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 1);
        return;
    }
    case 0xFB: { /* ISC abs,Y */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.y);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v + 1);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_sbc(r);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xFC: { /* NOP abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        (void)v;
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xFD: { /* SBC abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        if ((ea ^ base) & 0xFF00) cpu_read((uint16_t)(ea - 0x100), 0);
        uint8_t v = cpu_read(ea, CYC_POLL | CYC_DONE);
        cpu_sbc(v);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xFE: { /* INC abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v + 1); cpu_nz(r);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    case 0xFF: { /* ISC abs,X */
        b1 = cpu_read((uint16_t)(pc + 1), 0);
        b2 = cpu_read((uint16_t)(pc + 2), 0);
        uint16_t base = (uint16_t)(b1 | b2 << 8), ea = (uint16_t)(base + cpu.x);
        cpu_read((uint16_t)((base & 0xFF00) | (ea & 0xFF)), 0);
        uint8_t v = cpu_read(ea, 0), r;
        cpu_write(ea, v, 0);
        r = (uint8_t)(v + 1);
        cpu_write(ea, r, CYC_POLL | CYC_DONE);
        cpu_sbc(r);
        cpu.pc = (uint16_t)(pc + 3);
        return;
    }
    }
    (void)b1; (void)b2;
}
