set(NESRECOMP_PPU_IMPL "LLE" CACHE STRING "Cycle PPU implementation (LLE or HLE)")
set_property(CACHE NESRECOMP_PPU_IMPL PROPERTY STRINGS LLE HLE)
if(NESRECOMP_PPU_IMPL STREQUAL "LLE")
    add_compile_definitions(NESRECOMP_PPU_HLE=0)
elseif(NESRECOMP_PPU_IMPL STREQUAL "HLE")
    add_compile_definitions(NESRECOMP_PPU_HLE=1)
else()
    message(FATAL_ERROR "NESRECOMP_PPU_IMPL must be LLE or HLE")
endif()
message(STATUS "nesrecomp: cycle PPU implementation = ${NESRECOMP_PPU_IMPL} (build-fixed)")
