# Opt-in cycle backend for existing game projects. See PROJECTS.md.
include_guard(GLOBAL)

# recomp-ui (launcher + in-game menu, runner/cyc/cyc_ui.h) for windowed
# targets. NESRECOMP_RECOMP_UI names a checkout; empty uses the calling
# project's recomp-ui/ submodule when it carries what the cycle host needs
# (the runtime toast, the ROM-picker override); OFF, or NESRECOMP_HEADLESS,
# builds without it. recomp_ui.cmake has to be included here, at file scope:
# it enables C++ for the directory.
set(NESRECOMP_RECOMP_UI "" CACHE STRING "recomp-ui checkout for the cycle host's launcher and menu (empty: <source>/recomp-ui if usable; OFF: none)")
set(NESRECOMP_CYC_RECOMP_UI_ROOT "")
function(_nesrecomp_recomp_ui_usable dir out why)
    set(${out} FALSE PARENT_SCOPE)
    if(NOT EXISTS "${dir}/recomp_ui.cmake" OR NOT EXISTS "${dir}/src/recomp_runtime_ui.h")
        set(${why} "no recomp_ui.cmake / src/recomp_runtime_ui.h" PARENT_SCOPE)
        return()
    endif()
    file(READ "${dir}/src/recomp_runtime_ui.h" rui)
    file(READ "${dir}/src/recomp_launcher.h" launcher)
    if(NOT rui MATCHES "RECOMP_RUNTIME_UI_HAS_TOAST" OR NOT launcher MATCHES "RECOMP_LAUNCHER_HAS_ROM_PATTERNS"
       OR NOT launcher MATCHES "settings_bindings")
        set(${why} "it predates the runtime toast / ROM-picker override (recomp-ui feat/fds-disk-ui)" PARENT_SCOPE)
        return()
    endif()
    set(${out} TRUE PARENT_SCOPE)
endfunction()
if(NOT NESRECOMP_HEADLESS AND NOT NESRECOMP_RECOMP_UI STREQUAL "OFF")
    if(NESRECOMP_RECOMP_UI)
        get_filename_component(_nes_rui "${NESRECOMP_RECOMP_UI}" ABSOLUTE)
        _nesrecomp_recomp_ui_usable("${_nes_rui}" _nes_rui_ok _nes_rui_why)
        if(NOT _nes_rui_ok)
            message(FATAL_ERROR "NESRECOMP_RECOMP_UI=${_nes_rui}: ${_nes_rui_why}")
        endif()
    elseif(EXISTS "${CMAKE_SOURCE_DIR}/recomp-ui/recomp_ui.cmake")
        set(_nes_rui "${CMAKE_SOURCE_DIR}/recomp-ui")
        _nesrecomp_recomp_ui_usable("${_nes_rui}" _nes_rui_ok _nes_rui_why)
        if(NOT _nes_rui_ok)
            message(WARNING "${_nes_rui}: ${_nes_rui_why}; the cycle host builds without the launcher and menu "
                            "(bump the submodule, or set NESRECOMP_RECOMP_UI)")
        endif()
    endif()
    if(_nes_rui_ok)
        set(RECOMP_UI_ROOT "${_nes_rui}" CACHE PATH "Root directory of the recomp-ui launcher repo" FORCE)
        include("${_nes_rui}/recomp_ui.cmake")
        set(NESRECOMP_CYC_RECOMP_UI_ROOT "${_nes_rui}")
        message(STATUS "cycle backend: recomp-ui launcher and menu from ${_nes_rui}")
    endif()
endif()

function(nesrecomp_add_cycle_game target)
    cmake_parse_arguments(CYC "HEADLESS;NO_RECOMP_UI;MODS;HD_PACKS" "ROM;GAME_CONFIG;SEED_FILE;CAPTURE_FILE;RECOMPILER;BIOS;BOXART;GAME_ID;PLAYERS;ZAPPER_PORT;REGION;PASSWORD_SAVE;PASSWORD_SAVE_LABEL"
        "HOST_EXTRAS" ${ARGN})
    if(CYC_UNPARSED_ARGUMENTS OR NOT CYC_ROM)
        message(FATAL_ERROR "nesrecomp_add_cycle_game requires ROM; unknown arguments: ${CYC_UNPARSED_ARGUMENTS}")
    endif()
    set(cyc_dir "${CMAKE_CURRENT_FUNCTION_LIST_DIR}")
    get_filename_component(root "${cyc_dir}/../.." ABSOLUTE)
    find_package(Python3 3.11 REQUIRED COMPONENTS Interpreter)
    if(NOT CYC_RECOMPILER)
        if(CMAKE_CROSSCOMPILING)
            message(FATAL_ERROR "Cross builds require RECOMPILER pointing to a runnable host NESRecomp")
        endif()
        # Code generation determines the source list, so bootstrap the small
        # host compiler during configure, in its own build directory.
        set(host_build "${CMAKE_BINARY_DIR}/nesrecomp-host")
        set(host_args -G "${CMAKE_GENERATOR}" -DCMAKE_BUILD_TYPE=Release
            "-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}")
        if(CMAKE_GENERATOR_PLATFORM)
            list(APPEND host_args -A "${CMAKE_GENERATOR_PLATFORM}")
        endif()
        if(CMAKE_GENERATOR_TOOLSET)
            list(APPEND host_args -T "${CMAKE_GENERATOR_TOOLSET}")
        endif()
        if(CMAKE_GENERATOR_INSTANCE)
            list(APPEND host_args "-DCMAKE_GENERATOR_INSTANCE=${CMAKE_GENERATOR_INSTANCE}")
        endif()
        # The same tools as this build, not whatever the PATH finds first.
        if(NOT CMAKE_CONFIGURATION_TYPES)
            foreach(var CMAKE_MAKE_PROGRAM CMAKE_LINKER CMAKE_RC_COMPILER CMAKE_MT CMAKE_AR)
                if(${var})
                    list(APPEND host_args "-D${var}=${${var}}")
                endif()
            endforeach()
        endif()
        file(MAKE_DIRECTORY "${host_build}")
        execute_process(COMMAND "${CMAKE_COMMAND}" -S "${root}/recompiler" -B "${host_build}" ${host_args}
            RESULT_VARIABLE result OUTPUT_FILE "${host_build}/configure.log" ERROR_FILE "${host_build}/configure.err")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Host compiler configure failed (${result}); see ${host_build}/configure.err")
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" --build "${host_build}" --config Release --parallel 2
            RESULT_VARIABLE result OUTPUT_FILE "${host_build}/build.log" ERROR_FILE "${host_build}/build.err")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Host compiler build failed (${result}); see ${host_build}/build.log and build.err")
        endif()
        set(CYC_RECOMPILER "${host_build}/NESRecomp${CMAKE_EXECUTABLE_SUFFIX}")
        if(CMAKE_CONFIGURATION_TYPES)
            set(CYC_RECOMPILER "${host_build}/Release/NESRecomp${CMAKE_EXECUTABLE_SUFFIX}")
        endif()
        file(GLOB_RECURSE host_inputs CONFIGURE_DEPENDS
            "${root}/recompiler/src/*.c" "${root}/recompiler/src/*.h" "${root}/common/*.h")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
            ${host_inputs} "${root}/recompiler/CMakeLists.txt")
    endif()
    set(project_dir "${CMAKE_CURRENT_BINARY_DIR}/cycle-${target}")
    set(args --rom "${CYC_ROM}" --recompiler "${CYC_RECOMPILER}" --out "${project_dir}")
    if(CYC_GAME_CONFIG)
        list(APPEND args --game "${CYC_GAME_CONFIG}")
    endif()
    if(CYC_SEED_FILE)
        list(APPEND args --seeds "${CYC_SEED_FILE}")
    endif()
    if(CYC_CAPTURE_FILE)
        list(APPEND args --captures "${CYC_CAPTURE_FILE}")
    endif()
    if(CYC_BIOS)
        list(APPEND args --fds-bios "${CYC_BIOS}")
    endif()
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${root}/tools/cyc/prepare_project.py" ${args}
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cycle code generation failed (${result}):\n${output}\n${error}")
    endif()
    include("${project_dir}/sources.cmake")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
        ${CYC_PROJECT_DEPENDS} "${root}/tools/cyc/prepare_project.py")
    include("${cyc_dir}/cyc.cmake")
    add_executable(${target} ${NESRECOMP_CYC_SOURCES} ${CYC_PROJECT_SOURCES})
    target_compile_features(${target} PRIVATE c_std_11)
    target_include_directories(${target} PRIVATE ${NESRECOMP_CYC_INCLUDE_DIRS})
    target_link_libraries(${target} PRIVATE ${NESRECOMP_CYC_LIBRARIES})
    target_compile_definitions(${target} PRIVATE _CRT_SECURE_NO_WARNINGS)
    if(CYC_PASSWORD_SAVE)
        target_compile_definitions(${target} PRIVATE "CYC_GAME_PASSWORD_SAVE=\"${CYC_PASSWORD_SAVE}\"")
        if(CYC_PASSWORD_SAVE_LABEL)
            target_compile_definitions(${target} PRIVATE "CYC_GAME_PASSWORD_SAVE_LABEL=\"${CYC_PASSWORD_SAVE_LABEL}\"")
        endif()
    endif()
    if(CYC_PLAYERS)
        if(NOT CYC_PLAYERS MATCHES "^[1234]$")
            message(FATAL_ERROR "PLAYERS must be 1, 2, 3 or 4 (logical input seats; two physical NES ports)")
        endif()
        target_compile_definitions(${target} PRIVATE CYC_GAME_PLAYERS=${CYC_PLAYERS})
        if(CYC_PLAYERS GREATER 2)
            target_compile_definitions(${target} PRIVATE CYC_INPUT_PLAYERS=${CYC_PLAYERS})
        endif()
    endif()
    if(CYC_HOST_EXTRAS)
        # See cyc_host_extras.h for the game's optional host additions.
        # the game's additions (cyc_host_extras.h): its window, options,
        # per-frame work, compositor (cyc_render.h) and mods
        target_sources(${target} PRIVATE ${CYC_HOST_EXTRAS})
        set_property(TARGET ${target} PROPERTY NESRECOMP_CYC_HOST_EXTRAS TRUE)
    endif()
    if(CYC_REGION)
        if(CYC_REGION STREQUAL "NTSC")
            target_compile_definitions(${target} PRIVATE CYC_GAME_REGION=0)
        elseif(CYC_REGION STREQUAL "PAL")
            target_compile_definitions(${target} PRIVATE CYC_GAME_REGION=1)
        else()
            message(FATAL_ERROR "REGION must be NTSC or PAL")
        endif()
    endif()
    if(CYC_ZAPPER_PORT)
        if(NOT CYC_ZAPPER_PORT MATCHES "^[12]$")
            message(FATAL_ERROR "ZAPPER_PORT must be 1 or 2")
        endif()
        target_compile_definitions(${target} PRIVATE CYC_GAME_ZAPPER_PORT=${CYC_ZAPPER_PORT})
    endif()
    if(CYC_MODS)
        # The mod package runtime (runner/include/mod_runtime.h, docs/MOD_PACKAGES.md)
        # for this game's trusted plugins: packages target GAME_ID and the image's
        # identity (CRC32 of the cartridge payload after its iNES header, or of
        # the disk's side data), and the launcher gets its Mods screen.
        if(NOT CYC_GAME_ID)
            message(FATAL_ERROR "nesrecomp_add_cycle_game(${target} MODS) needs GAME_ID, the id mod manifests target")
        endif()
        if(NOT CMAKE_CXX_COMPILER_LOADED)
            message(FATAL_ERROR "nesrecomp_add_cycle_game(${target} MODS): the mod runtime is C++; declare CXX in project()")
        endif()
        target_sources(${target} PRIVATE "${root}/runner/src/mod_runtime.cpp" "${root}/runner/src/crc32.c")
        target_include_directories(${target} PRIVATE "${root}/runner/include")
        target_compile_features(${target} PRIVATE cxx_std_17)
        target_compile_definitions(${target} PRIVATE NESRECOMP_ENABLE_MODS=1 "CYC_MOD_GAME_ID=\"${CYC_GAME_ID}\""
            "CYC_MOD_ROM_CRC32=\"${CYC_PROJECT_MOD_CRC32}\"")
        set(RECOMP_UI_ENABLE_MODS ON)
    endif()
    if(CYC_HD_PACKS)
        if(NOT CYC_MODS)
            message(FATAL_ERROR "HD_PACKS requires MODS GAME_ID")
        endif()
        include("${cyc_dir}/hdpack.cmake")
        nesrecomp_cyc_enable_hdpack(${target} MODS)
    endif()
    if(NOT CYC_HEADLESS)
        nesrecomp_cyc_enable_sdl(${target})
        if(NESRECOMP_CYC_RECOMP_UI_ROOT AND NOT CYC_NO_RECOMP_UI)
            set(boxart "")
            if(CYC_BOXART)
                set(boxart BOXART "${CYC_BOXART}")
            endif()
            nesrecomp_cyc_enable_recomp_ui(${target} ${boxart} ROM_SHA256 "${CYC_PROJECT_LAUNCHER_SHA256}")
        endif()
    elseif(CYC_HOST_EXTRAS)
        message(STATUS "${target}: headless; HOST_EXTRAS only matter to the window")
    endif()
    set_property(TARGET ${target} PROPERTY NESRECOMP_ROM "${CYC_PROJECT_ROM}")
    message(STATUS "${target}: cycle backend, ROM SHA256 ${CYC_PROJECT_ROM_SHA256}")
    if(CYC_MODS)
        message(STATUS "${target}: mods for ${CYC_GAME_ID}, image identity ${CYC_PROJECT_MOD_CRC32}")
    endif()
endfunction()
