# Opt-in cycle backend for existing game projects. See PROJECTS.md.
include_guard(GLOBAL)

function(nesrecomp_add_cycle_game target)
    cmake_parse_arguments(CYC "HEADLESS" "ROM;GAME_CONFIG;SEED_FILE;RECOMPILER" "" ${ARGN})
    if(CYC_UNPARSED_ARGUMENTS OR NOT CYC_ROM)
        message(FATAL_ERROR "nesrecomp_add_cycle_game requires ROM; unknown arguments: ${CYC_UNPARSED_ARGUMENTS}")
    endif()
    set(cyc_dir "${CMAKE_CURRENT_FUNCTION_LIST_DIR}")
    get_filename_component(root "${cyc_dir}/../.." ABSOLUTE)
    find_package(Python3 3.11 REQUIRED COMPONENTS Interpreter)
    if(NOT CYC_RECOMPILER)
        if(CMAKE_CROSSCOMPILING)
            message(FATAL_ERROR "Cross builds require RECOMPILER pointing to a runnable host NESRecomp")
        endif()
        # Code generation determines the source list, so bootstrap the small
        # host compiler during configure, in its own build directory.
        set(host_build "${CMAKE_BINARY_DIR}/nesrecomp-host")
        set(host_args -G "${CMAKE_GENERATOR}" -DCMAKE_BUILD_TYPE=Release
            "-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}")
        if(CMAKE_GENERATOR_PLATFORM)
            list(APPEND host_args -A "${CMAKE_GENERATOR_PLATFORM}")
        endif()
        if(CMAKE_GENERATOR_TOOLSET)
            list(APPEND host_args -T "${CMAKE_GENERATOR_TOOLSET}")
        endif()
        file(MAKE_DIRECTORY "${host_build}")
        execute_process(COMMAND "${CMAKE_COMMAND}" -S "${root}/recompiler" -B "${host_build}" ${host_args}
            RESULT_VARIABLE result OUTPUT_FILE "${host_build}/configure.log" ERROR_FILE "${host_build}/configure.err")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Host compiler configure failed (${result}); see ${host_build}/configure.err")
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" --build "${host_build}" --config Release --parallel 2
            RESULT_VARIABLE result OUTPUT_FILE "${host_build}/build.log" ERROR_FILE "${host_build}/build.err")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Host compiler build failed (${result}); see ${host_build}/build.log and build.err")
        endif()
        set(CYC_RECOMPILER "${host_build}/NESRecomp${CMAKE_EXECUTABLE_SUFFIX}")
        if(CMAKE_CONFIGURATION_TYPES)
            set(CYC_RECOMPILER "${host_build}/Release/NESRecomp${CMAKE_EXECUTABLE_SUFFIX}")
        endif()
        file(GLOB_RECURSE host_inputs CONFIGURE_DEPENDS
            "${root}/recompiler/src/*.c" "${root}/recompiler/src/*.h" "${root}/common/*.h")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
            ${host_inputs} "${root}/recompiler/CMakeLists.txt")
    endif()
    set(project_dir "${CMAKE_CURRENT_BINARY_DIR}/cycle-${target}")
    set(args --rom "${CYC_ROM}" --recompiler "${CYC_RECOMPILER}" --out "${project_dir}")
    if(CYC_GAME_CONFIG)
        list(APPEND args --game "${CYC_GAME_CONFIG}")
    endif()
    if(CYC_SEED_FILE)
        list(APPEND args --seeds "${CYC_SEED_FILE}")
    endif()
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${root}/tools/cyc/prepare_project.py" ${args}
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cycle code generation failed (${result}):\n${output}\n${error}")
    endif()
    include("${project_dir}/sources.cmake")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
        ${CYC_PROJECT_DEPENDS} "${root}/tools/cyc/prepare_project.py")
    include("${cyc_dir}/cyc.cmake")
    add_executable(${target} ${NESRECOMP_CYC_SOURCES} ${CYC_PROJECT_SOURCES})
    target_compile_features(${target} PRIVATE c_std_11)
    target_include_directories(${target} PRIVATE ${NESRECOMP_CYC_INCLUDE_DIRS})
    target_link_libraries(${target} PRIVATE ${NESRECOMP_CYC_LIBRARIES})
    target_compile_definitions(${target} PRIVATE _CRT_SECURE_NO_WARNINGS)
    if(NOT CYC_HEADLESS)
        nesrecomp_cyc_enable_sdl(${target})
    endif()
    set_property(TARGET ${target} PROPERTY NESRECOMP_ROM "${CYC_PROJECT_ROM}")
    message(STATUS "${target}: cycle backend, ROM SHA256 ${CYC_PROJECT_ROM_SHA256}")
endfunction()
